/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Values: nonexist,uninit,active,frozen
 */
@Serializable
enum class AccountStatus(val value: String) {
    @SerialName(value = "nonexist")
    nonexist("nonexist"),
    @SerialName(value = "uninit")
    uninit("uninit"),
    @SerialName(value = "active")
    active("active"),
    @SerialName(value = "frozen")
    frozen("frozen");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is AccountStatus) "$data" else null

        /**
         * Returns a valid [AccountStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AccountStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

