/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class BlockchainConfig11(
    @SerialName(value = "normal_params")
    val normalParams: ConfigProposalSetup,
    @SerialName(value = "critical_params")
    val criticalParams: ConfigProposalSetup
) {
}

