/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class BlockchainBlock(
    @SerialName(value = "tx_quantity")
    val txQuantity: Int,
    @SerialName(value = "value_flow")
    val valueFlow: BlockValueFlow,
    @SerialName(value = "workchain_id")
    val workchainId: Int,
    @SerialName(value = "shard")
    val shard: String,
    @SerialName(value = "seqno")
    val seqno: Int,
    @SerialName(value = "root_hash")
    val rootHash: String,
    @SerialName(value = "file_hash")
    val fileHash: String,
    @SerialName(value = "global_id")
    val globalId: Int,
    @SerialName(value = "version")
    val version: Int,
    @SerialName(value = "after_merge")
    val afterMerge: Boolean,
    @SerialName(value = "before_split")
    val beforeSplit: Boolean,
    @SerialName(value = "after_split")
    val afterSplit: Boolean,
    @SerialName(value = "want_split")
    val wantSplit: Boolean,
    @SerialName(value = "want_merge")
    val wantMerge: Boolean,
    @SerialName(value = "key_block")
    val keyBlock: Boolean,
    @SerialName(value = "gen_utime")
    val genUtime: Long,
    @SerialName(value = "start_lt")
    val startLt: Long,
    @SerialName(value = "end_lt")
    val endLt: Long,
    @SerialName(value = "vert_seqno")
    val vertSeqno: Int,
    @SerialName(value = "gen_catchain_seqno")
    val genCatchainSeqno: Int,
    @SerialName(value = "min_ref_mc_seqno")
    val minRefMcSeqno: Int,
    @SerialName(value = "prev_key_block_seqno")
    val prevKeyBlockSeqno: Int,
    @SerialName(value = "prev_refs")
    val prevRefs: List<String>,
    @SerialName(value = "in_msg_descr_length")
    val inMsgDescrLength: Long,
    @SerialName(value = "out_msg_descr_length")
    val outMsgDescrLength: Long,
    @SerialName(value = "rand_seed")
    val randSeed: String,
    @SerialName(value = "created_by")
    val createdBy: String,
    @SerialName(value = "gen_software_version")
    val genSoftwareVersion: Int? = null,
    @SerialName(value = "gen_software_capabilities")
    val genSoftwareCapabilities: Long? = null,
    @SerialName(value = "master_ref")
    val masterRef: String? = null
) {
}

