/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class DefiAsset(
    @Contextual @SerialName(value = "type")
    val type: DefiAssetType,

    /* amount in minimal units of the locked asset */
    @SerialName(value = "amount")
    val amount: String,
    @SerialName(value = "defi_provider")
    val defiProvider: DefiProvider,
    @SerialName(value = "locked_asset")
    val lockedAsset: DefiLockedAsset,
    @SerialName(value = "pool_address")
    val poolAddress: String? = null,
    @SerialName(value = "asset_address")
    val assetAddress: String? = null
) {
}

