/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class DnsExpiringItemsInner(
    @SerialName(value = "expiring_at")
    val expiringAt: Long,
    @SerialName(value = "name")
    val name: String,
    @SerialName(value = "dns_item")
    val dnsItem: NftItem? = null
) {
}

