/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class DnsRecord(
    @SerialName(value = "sites")
    val sites: List<String>,
    @SerialName(value = "wallet")
    val wallet: WalletDNS? = null,
    @SerialName(value = "next_resolver")
    val nextResolver: String? = null,

    /* tonstorage bag id */
    @SerialName(value = "storage")
    val storage: String? = null,
    @SerialName(value = "picture")
    val picture: PictureDNS? = null
) {
}

