/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class DomainInfo(
    @SerialName(value = "name")
    val name: String,

    /* date of expiring. optional. not all domain in ton has expiration date */
    @SerialName(value = "expiring_at")
    val expiringAt: Long? = null,
    @SerialName(value = "item")
    val item: NftItem? = null
) {
}

