/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class GaslessConfig(
    /* sending excess to this address decreases the commission of a gasless transfer */
    @SerialName(value = "relay_address")
    val relayAddress: String,

    /* list of jettons, any of them can be used to pay for gas */
    @SerialName(value = "gas_jettons")
    val gasJettons: List<GaslessConfigGasJettonsInner>
) {
}

