/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class GetRawAccountState200Response(
    @SerialName(value = "id")
    val id: BlockRaw,
    @SerialName(value = "shardblk")
    val shardblk: BlockRaw,
    @SerialName(value = "shard_proof")
    val shardProof: String,
    @SerialName(value = "proof")
    val proof: String,
    @SerialName(value = "state")
    val state: String
) {
}

