/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class JettonBurnAction(
    @SerialName(value = "sender")
    val sender: AccountAddress,
    @SerialName(value = "senders_wallet")
    val sendersWallet: String,

    /* amount in quanta of tokens */
    @SerialName(value = "amount")
    val amount: String,
    @SerialName(value = "jetton")
    val jetton: JettonPreview
) {
}

