/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class JettonInfo(
    @SerialName(value = "mintable")
    val mintable: Boolean,
    @SerialName(value = "total_supply")
    val totalSupply: String,
    @SerialName(value = "metadata")
    val metadata: JettonMetadata,
    @SerialName(value = "preview")
    val preview: String,

    @Contextual @SerialName(value = "verification")
    val verification: JettonVerificationType,
    @SerialName(value = "holders_count")
    val holdersCount: Int,
    @SerialName(value = "admin")
    val admin: AccountAddress? = null,
    @SerialName(value = "scaled_ui")
    val scaledUi: ScaledUI? = null
) {
}

