/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class JettonBridgePrices(
    @SerialName(value = "bridge_burn_fee")
    val bridgeBurnFee: Long,
    @SerialName(value = "bridge_mint_fee")
    val bridgeMintFee: Long,
    @SerialName(value = "wallet_min_gram_for_storage")
    val walletMinGramForStorage: Long,
    @SerialName(value = "wallet_gas_consumption")
    val walletGasConsumption: Long,
    @SerialName(value = "minter_min_gram_for_storage")
    val minterMinGramForStorage: Long,
    @SerialName(value = "discover_gas_consumption")
    val discoverGasConsumption: Long,

    /* this field will gone after Sept. 2026, use wallet_min_gram_for_storage instead */
    @SerialName(value = "wallet_min_tons_for_storage")
    @Deprecated(message = "This property is deprecated.")
    val walletMinTonsForStorage: Long? = null,

    /* this field will gone after Sept. 2026, use wallet_min_gram_for_storage instead */
    @SerialName(value = "minter_min_tons_for_storage")
    @Deprecated(message = "This property is deprecated.")
    val minterMinTonsForStorage: Long? = null
) {
}

