/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class MigrationTransaction(
    /* wallet seqno baked into the unsigned body */
    @SerialName(value = "seqno")
    val seqno: Int,

    /* base64 BOC of the unsigned wallet body. The body type is determined by (wallet_version, sponsored): for v3/v4 it is always the external body — sign its hash, prepend the signature, wrap in an external message; for w5 with sponsored=false it is the external body with the signature appended as the trailing 512 bits; for w5 with sponsored=true it is the internal_signed body — sign and wrap it for /v2/gasless/send as in the gasless flow.  */
    @SerialName(value = "boc")
    val boc: String,

    /* ordered raw internal messages carried by this transaction — the cells the wallet resends. These are what populate the payload/actions.  */
    @SerialName(value = "messages")
    val messages: List<MigrationOutMessage>,
    @SerialName(value = "emulation")
    val emulation: MessageConsequences,

    /* TON burned as network fees by this transaction, in nanotons — the sum over every transaction in `emulation.trace`. For a transfer batch this is only part of the gas attached to its messages: the transfers name the destination wallet as response_destination, so the unburned remainder arrives there instead of returning to the source. For the final balance sweep it is the fee deducted from the swept amount. When `sponsored` is true these fees are covered by the relay, which charges `commission` instead.  */
    @SerialName(value = "gas_spent")
    val gasSpent: Long,

    /* true — the Battery relay pays gas for this transaction; submit it via /v2/gasless/send. false — self-paid; sign and broadcast via /v2/blockchain/message as usual (e.g. the final TON sweep).  */
    @SerialName(value = "sponsored")
    val sponsored: Boolean? = false,

    /* gasless only; the relay commission in indivisible gas-jetton units, embedded in the boc as a jetton transfer to the relay. Exact for the first transaction; an estimate for later ones (re-running prepare refreshes it).  */
    @SerialName(value = "commission")
    val commission: String? = null,

    /* base64 BOC of the wallet StateInit (code + data). Present only on the first transaction when the source wallet is not yet initialized  */
    @SerialName(value = "state_init")
    val stateInit: String? = null
) {
}

