/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class OracleRequestAction(
    @SerialName(value = "requester")
    val requester: AccountAddress,
    @SerialName(value = "response_to")
    val responseTo: AccountAddress,
    @SerialName(value = "price_feeds")
    val priceFeeds: List<OraclePriceFeed>
) {
}

