/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class PoolImplementation(
    @SerialName(value = "name")
    val name: String,
    @SerialName(value = "description")
    val description: String,
    @SerialName(value = "url")
    val url: String,
    @SerialName(value = "socials")
    val socials: List<String>
) {
}

