/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Price(
    @Contextual @SerialName(value = "currency_type")
    val currencyType: CurrencyType,
    @SerialName(value = "value")
    val `value`: String,
    @SerialName(value = "decimals")
    val decimals: Int,
    @SerialName(value = "token_name")
    val tokenName: String,

    @Contextual @SerialName(value = "verification")
    val verification: TrustType,
    @SerialName(value = "image")
    val image: String,
    @SerialName(value = "jetton")
    val jetton: String? = null
) {
}

