/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class SizeLimitsConfig(
    @SerialName(value = "max_msg_bits")
    val maxMsgBits: Long,
    @SerialName(value = "max_msg_cells")
    val maxMsgCells: Long,
    @SerialName(value = "max_library_cells")
    val maxLibraryCells: Long,
    @SerialName(value = "max_vm_data_depth")
    val maxVmDataDepth: Int,
    @SerialName(value = "max_ext_msg_size")
    val maxExtMsgSize: Long,
    @SerialName(value = "max_ext_msg_depth")
    val maxExtMsgDepth: Int,
    @SerialName(value = "max_acc_state_cells")
    val maxAccStateCells: Long? = null,
    @SerialName(value = "max_acc_state_bits")
    val maxAccStateBits: Long? = null
) {
}

