/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class SmartContractAction(
    @SerialName(value = "executor")
    val executor: AccountAddress,
    @SerialName(value = "contract")
    val `contract`: AccountAddress,

    /* amount in nanotons */
    @SerialName(value = "ton_attached")
    val tonAttached: Long,
    @SerialName(value = "operation")
    val operation: String,
    @SerialName(value = "payload")
    val payload: String? = null,
    @SerialName(value = "refund")
    val refund: Refund? = null
) {
}

