/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class StoragePhase(
    @SerialName(value = "fees_collected")
    val feesCollected: Long,

    @Contextual @SerialName(value = "status_change")
    val statusChange: AccStatusChange,
    @SerialName(value = "fees_due")
    val feesDue: Long? = null
) {
}

