/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class TonConnectProofRequestProof(
    @SerialName(value = "timestamp")
    val timestamp: Long,
    @SerialName(value = "domain")
    val domain: TonConnectProofRequestProofDomain,
    @SerialName(value = "signature")
    val signature: String,
    @SerialName(value = "payload")
    val payload: String,
    @SerialName(value = "state_init")
    val stateInit: String? = null
) {
}

