/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Transaction(
    @SerialName(value = "hash")
    val hash: String,
    @SerialName(value = "lt")
    val lt: Long,
    @SerialName(value = "account")
    val account: AccountAddress,
    @SerialName(value = "success")
    val success: Boolean,
    @SerialName(value = "utime")
    val utime: Long,

    @Contextual @SerialName(value = "orig_status")
    val origStatus: AccountStatus,

    @Contextual @SerialName(value = "end_status")
    val endStatus: AccountStatus,
    @SerialName(value = "total_fees")
    val totalFees: Long,
    @SerialName(value = "end_balance")
    val endBalance: Long,

    @Contextual @SerialName(value = "transaction_type")
    val transactionType: TransactionType,
    @SerialName(value = "state_update_old")
    val stateUpdateOld: String,
    @SerialName(value = "state_update_new")
    val stateUpdateNew: String,
    @SerialName(value = "out_msgs")
    val outMsgs: List<Message>,
    @SerialName(value = "block")
    val block: String,
    @SerialName(value = "aborted")
    val aborted: Boolean,
    @SerialName(value = "destroyed")
    val destroyed: Boolean,

    /* hex encoded boc with raw transaction */
    @SerialName(value = "raw")
    val raw: String,
    @SerialName(value = "in_msg")
    val inMsg: Message? = null,
    @SerialName(value = "prev_trans_hash")
    val prevTransHash: String? = null,
    @SerialName(value = "prev_trans_lt")
    val prevTransLt: Long? = null,
    @SerialName(value = "compute_phase")
    val computePhase: ComputePhase? = null,
    @SerialName(value = "storage_phase")
    val storagePhase: StoragePhase? = null,
    @SerialName(value = "credit_phase")
    val creditPhase: CreditPhase? = null,
    @SerialName(value = "action_phase")
    val actionPhase: ActionPhase? = null,

    @Contextual @SerialName(value = "bounce_phase")
    val bouncePhase: BouncePhaseType? = null
) {
}

