/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class ValidatorRewardEntry(
    /* Position sorted by effective stake (descending). */
    @SerialName(value = "rank")
    val rank: Int,

    /* Validator's public key (hex-encoded Ed25519). */
    @SerialName(value = "public_key")
    val publicKey: String,

    /* amount in nanotons */
    @SerialName(value = "effective_stake")
    val effectiveStake: Long,

    /* Fraction of total effective stake (0–1). */
    @SerialName(value = "weight")
    val weight: Double,

    /* amount in nanotons */
    @SerialName(value = "reward")
    val reward: Long,

    /* Pool smart contract address (bounceable, base64url). */
    @SerialName(value = "pool")
    val pool: String? = null,

    /* Contract type detected by code hash. */
    @SerialName(value = "pool_type")
    val poolType: PoolType? = null,
    @SerialName(value = "owner_address")
    val ownerAddress: String? = null,
    @SerialName(value = "validator_address")
    val validatorAddress: String? = null,

    /* amount in nanotons */
    @SerialName(value = "validator_stake")
    val validatorStake: Long? = null,

    /* amount in nanotons */
    @SerialName(value = "nominators_stake")
    val nominatorsStake: Long? = null,

    /* Total funds deposited by the pool: effective_stake + credit (leftover balance kept in the elector contract after election).  */
    @SerialName(value = "total_stake")
    val totalStake: Long? = null,

    /* Fraction of staking rewards kept by the validator (0.3 = 30%). */
    @SerialName(value = "validator_reward_share")
    val validatorRewardShare: Double? = null,
    @SerialName(value = "nominators_count")
    val nominatorsCount: Int? = null,
    @SerialName(value = "nominators")
    val nominators: List<NominatorRewardEntry>? = null
) {
    /**
     * Contract type detected by code hash.
     *
     * Values: nominatorMinusPoolMinusV1Period0,singleMinusNominatorMinusPoolMinusV1Period0,singleMinusNominatorMinusPoolMinusV1Period1,other
     */
    @Serializable
    enum class PoolType(val value: String) {
        @SerialName(value = "nominator-pool-v1.0") nominatorMinusPoolMinusV1Period0("nominator-pool-v1.0"),
        @SerialName(value = "single-nominator-pool-v1.0") singleMinusNominatorMinusPoolMinusV1Period0("single-nominator-pool-v1.0"),
        @SerialName(value = "single-nominator-pool-v1.1") singleMinusNominatorMinusPoolMinusV1Period1("single-nominator-pool-v1.1"),
        @SerialName(value = "other") other("other");
    }
}
