/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class ValidatorsResponse(
    /* Server-side response time in milliseconds. */
    @SerialName(value = "response_time_ms")
    val responseTimeMs: Long,
    @SerialName(value = "block")
    val block: BlockInfo,
    @SerialName(value = "validation_round")
    val validationRound: RoundInfo,

    /* Current election ID (electAt timestamp). */
    @SerialName(value = "election_id")
    val electionId: Long,

    /* amount in nanotons */
    @SerialName(value = "elector_balance")
    val electorBalance: Long,

    /* amount in nanotons */
    @SerialName(value = "total_stake")
    val totalStake: Long,

    /* amount in nanotons */
    @SerialName(value = "reward_per_block")
    val rewardPerBlock: Long,
    @SerialName(value = "validators")
    val validators: List<ValidatorRewardEntry>,

    /* Election ID of the round immediately before this one. */
    @SerialName(value = "prev_election_id")
    val prevElectionId: Long? = null,

    /* Election ID of the round immediately after this one. Omitted when the current round is not yet finished (next round not known).  */
    @SerialName(value = "next_election_id")
    val nextElectionId: Long? = null
) {
}

