/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tonapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class WithdrawStakeRequestAction(
    @SerialName(value = "staker")
    val staker: AccountAddress,
    @SerialName(value = "pool")
    val pool: AccountAddress,

    @Contextual @SerialName(value = "implementation")
    val implementation: PoolImplementationType,
    @SerialName(value = "amount")
    val amount: Long? = null
) {
}

