/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param atType 
 */


data class DexSwapStatus200ResponseOneOf1 (

    @Json(name = "@type")
    val atType: DexSwapStatus200ResponseOneOf1.AtType

) {

    /**
     * 
     *
     * Values: NotFound
     */
    @JsonClass(generateAdapter = false)
    enum class AtType(val value: kotlin.String) {
        @Json(name = "NotFound") NotFound("NotFound");
    }
}

