/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param address NFT address
 * @param createTimestamp NFT creation timestamp
 * @param minUnstakeTimestamp Minimal unstake timestamp
 * @param nonclaimedRewards Nonclaimed rewards
 * @param stakedTokens Amount of staked tokens
 * @param status NFT status
 */


data class FarmNftInfoSchema (

    /* NFT address */
    @Json(name = "address")
    val address: kotlin.String,

    /* NFT creation timestamp */
    @Json(name = "create_timestamp")
    val createTimestamp: kotlin.String,

    /* Minimal unstake timestamp */
    @Json(name = "min_unstake_timestamp")
    val minUnstakeTimestamp: kotlin.String,

    /* Nonclaimed rewards */
    @Json(name = "nonclaimed_rewards")
    val nonclaimedRewards: kotlin.String,

    /* Amount of staked tokens */
    @Json(name = "staked_tokens")
    val stakedTokens: kotlin.String,

    /* NFT status */
    @Json(name = "status")
    val status: kotlin.String

)

