/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.stonfiapi.models.PoolStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param since Time since the stats are requested (YYYY-MM-DDTHH:MM:SS)
 * @param stats Stats of each pool
 * @param uniqueWalletsCount Number of unique wallets operated in pool
 * @param until Time until the stats are requested (YYYY-MM-DDTHH:MM:SS)
 */


data class GetPoolStats200Response (

    /* Time since the stats are requested (YYYY-MM-DDTHH:MM:SS) */
    @Json(name = "since")
    val since: kotlin.String,

    /* Stats of each pool */
    @Json(name = "stats")
    val stats: kotlin.collections.List<PoolStats>,

    /* Number of unique wallets operated in pool */
    @Json(name = "unique_wallets_count")
    val uniqueWalletsCount: kotlin.Long,

    /* Time until the stats are requested (YYYY-MM-DDTHH:MM:SS) */
    @Json(name = "until")
    val until: kotlin.String

)

