/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.apis.JettonApi
import io.stonfiapi.models.GetWalletAddress200Response

class JettonApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JettonApi
        //val apiInstance = JettonApi()

        // to test getWalletAddress
        should("test getWalletAddress") {
            // uncomment below to test getWalletAddress
            //val addrStr : kotlin.String = addrStr_example // kotlin.String | 
            //val ownerAddress : kotlin.String = EQCM3B12QK1e4yZSf8GtBRT0aLMNyEsBc_DhVfRRtOEffLez // kotlin.String | Address of the owner
            //val result : GetWalletAddress200Response = apiInstance.getWalletAddress(addrStr, ownerAddress)
            //result shouldBe ("TODO")
        }

    }
}
