/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.apis.StatsApi
import io.stonfiapi.models.GetDexStats200Response
import io.stonfiapi.models.GetOperationStats200Response
import io.stonfiapi.models.GetPoolStats200Response

class StatsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatsApi
        //val apiInstance = StatsApi()

        // to test getDexStats
        should("test getDexStats") {
            // uncomment below to test getDexStats
            //val since : kotlin.String = 2023-06-01T12:34:56 // kotlin.String | Time since stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val until : kotlin.String = 2023-06-02T23:59:59 // kotlin.String | Time until stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val result : GetDexStats200Response = apiInstance.getDexStats(since, until)
            //result shouldBe ("TODO")
        }

        // to test getOperationStats
        should("test getOperationStats") {
            // uncomment below to test getOperationStats
            //val since : kotlin.String = 2023-06-01T12:34:56 // kotlin.String | Time since the stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val until : kotlin.String = 2023-06-02T23:59:59 // kotlin.String | Time until pool stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val result : GetOperationStats200Response = apiInstance.getOperationStats(since, until)
            //result shouldBe ("TODO")
        }

        // to test getPoolStats
        should("test getPoolStats") {
            // uncomment below to test getPoolStats
            //val since : kotlin.String = 2023-06-01T12:34:56 // kotlin.String | Time since the stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val until : kotlin.String = 2023-06-02T23:59:59 // kotlin.String | Time until pool stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val result : GetPoolStats200Response = apiInstance.getPoolStats(since, until)
            //result shouldBe ("TODO")
        }

    }
}
