/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.apis.WalletsApi
import io.stonfiapi.models.GetAssetList200Response
import io.stonfiapi.models.GetFarmList200Response
import io.stonfiapi.models.GetOperationStats200Response
import io.stonfiapi.models.GetPoolList200Response

class WalletsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WalletsApi
        //val apiInstance = WalletsApi()

        // to test getWalletAssets
        should("test getWalletAssets") {
            // uncomment below to test getWalletAssets
            //val addrStr : kotlin.String = addrStr_example // kotlin.String | 
            //val result : GetAssetList200Response = apiInstance.getWalletAssets(addrStr)
            //result shouldBe ("TODO")
        }

        // to test getWalletFarm
        should("test getWalletFarm") {
            // uncomment below to test getWalletFarm
            //val addrStr : kotlin.String = addrStr_example // kotlin.String | 
            //val result : GetFarmList200Response = apiInstance.getWalletFarm(addrStr)
            //result shouldBe ("TODO")
        }

        // to test getWalletOperations
        should("test getWalletOperations") {
            // uncomment below to test getWalletOperations
            //val addrStr : kotlin.String = addrStr_example // kotlin.String | 
            //val since : kotlin.String = 2023-06-01T12:34:56 // kotlin.String | Time since the stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val until : kotlin.String = 2023-06-02T23:59:59 // kotlin.String | Time until pool stats are requested (YYYY-MM-DDTHH:MM:SS)
            //val opType : kotlin.String = SendLiquidity // kotlin.String | target op type
            //val result : GetOperationStats200Response = apiInstance.getWalletOperations(addrStr, since, until, opType)
            //result shouldBe ("TODO")
        }

        // to test getWalletPools
        should("test getWalletPools") {
            // uncomment below to test getWalletPools
            //val addrStr : kotlin.String = addrStr_example // kotlin.String | 
            //val result : GetPoolList200Response = apiInstance.getWalletPools(addrStr)
            //result shouldBe ("TODO")
        }

    }
}
