org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxMetaspaceSize=1g

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.vfs.watch=true
org.gradle.classloaderscope.strict=true
systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false

kotlin.daemon.jvmargs=-Xmx6g
kotlin.code.style=official
kotlin.incremental=true
kotlin.compiler.incremental=true

android.onlyEnableUnitTestForTheTestedBuildType=true
android.experimental.testOptions.managedDevices.maxConcurrentDevices=1
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.nonFinalResIds=true
#android.defaults.buildfeatures.buildconfig=false
