/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.AccountStaking
import io.tonapi.models.AccountStakingInfo

class AccountStakingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountStaking
        //val modelInstance = AccountStaking()

        // to test the property `pools`
        should("test pools") {
            // uncomment below to test the property
            //modelInstance.pools shouldBe ("TODO")
        }

    }
}
