/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.AccountStorageInfo

class AccountStorageInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountStorageInfo
        //val modelInstance = AccountStorageInfo()

        // to test the property `usedCells`
        should("test usedCells") {
            // uncomment below to test the property
            //modelInstance.usedCells shouldBe ("TODO")
        }

        // to test the property `usedBits`
        should("test usedBits") {
            // uncomment below to test the property
            //modelInstance.usedBits shouldBe ("TODO")
        }

        // to test the property `usedPublicCells`
        should("test usedPublicCells") {
            // uncomment below to test the property
            //modelInstance.usedPublicCells shouldBe ("TODO")
        }

        // to test the property `lastPaid`
        should("test lastPaid") {
            // uncomment below to test the property
            //modelInstance.lastPaid shouldBe ("TODO")
        }

        // to test the property `duePayment`
        should("test duePayment") {
            // uncomment below to test the property
            //modelInstance.duePayment shouldBe ("TODO")
        }

    }
}
