/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.ActionSimplePreview
import io.tonapi.models.AccountAddress

class ActionSimplePreviewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionSimplePreview
        //val modelInstance = ActionSimplePreview()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `accounts`
        should("test accounts") {
            // uncomment below to test the property
            //modelInstance.accounts shouldBe ("TODO")
        }

        // to test the property `actionImage` - a link to an image for this particular action.
        should("test actionImage") {
            // uncomment below to test the property
            //modelInstance.actionImage shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `valueImage` - a link to an image that depicts this action's asset.
        should("test valueImage") {
            // uncomment below to test the property
            //modelInstance.valueImage shouldBe ("TODO")
        }

    }
}
