/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.AddressParse200Response
import io.tonapi.models.AddressParse200ResponseBounceable

class AddressParse200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddressParse200Response
        //val modelInstance = AddressParse200Response()

        // to test the property `rawForm`
        should("test rawForm") {
            // uncomment below to test the property
            //modelInstance.rawForm shouldBe ("TODO")
        }

        // to test the property `bounceable`
        should("test bounceable") {
            // uncomment below to test the property
            //modelInstance.bounceable shouldBe ("TODO")
        }

        // to test the property `nonBounceable`
        should("test nonBounceable") {
            // uncomment below to test the property
            //modelInstance.nonBounceable shouldBe ("TODO")
        }

        // to test the property `givenType`
        should("test givenType") {
            // uncomment below to test the property
            //modelInstance.givenType shouldBe ("TODO")
        }

        // to test the property `testOnly`
        should("test testOnly") {
            // uncomment below to test the property
            //modelInstance.testOnly shouldBe ("TODO")
        }

    }
}
