/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.AddressParse200ResponseBounceable

class AddressParse200ResponseBounceableTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddressParse200ResponseBounceable
        //val modelInstance = AddressParse200ResponseBounceable()

        // to test the property `b64`
        should("test b64") {
            // uncomment below to test the property
            //modelInstance.b64 shouldBe ("TODO")
        }

        // to test the property `b64url`
        should("test b64url") {
            // uncomment below to test the property
            //modelInstance.b64url shouldBe ("TODO")
        }

    }
}
