/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.BlockchainConfig28

class BlockchainConfig28Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockchainConfig28
        //val modelInstance = BlockchainConfig28()

        // to test the property `mcCatchainLifetime`
        should("test mcCatchainLifetime") {
            // uncomment below to test the property
            //modelInstance.mcCatchainLifetime shouldBe ("TODO")
        }

        // to test the property `shardCatchainLifetime`
        should("test shardCatchainLifetime") {
            // uncomment below to test the property
            //modelInstance.shardCatchainLifetime shouldBe ("TODO")
        }

        // to test the property `shardValidatorsLifetime`
        should("test shardValidatorsLifetime") {
            // uncomment below to test the property
            //modelInstance.shardValidatorsLifetime shouldBe ("TODO")
        }

        // to test the property `shardValidatorsNum`
        should("test shardValidatorsNum") {
            // uncomment below to test the property
            //modelInstance.shardValidatorsNum shouldBe ("TODO")
        }

        // to test the property `flags`
        should("test flags") {
            // uncomment below to test the property
            //modelInstance.flags shouldBe ("TODO")
        }

        // to test the property `shuffleMcValidators`
        should("test shuffleMcValidators") {
            // uncomment below to test the property
            //modelInstance.shuffleMcValidators shouldBe ("TODO")
        }

    }
}
