/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.BlockchainAccountInspect
import io.tonapi.models.BlockchainAccountInspectMethodsInner

class BlockchainAccountInspectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockchainAccountInspect
        //val modelInstance = BlockchainAccountInspect()

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `codeHash`
        should("test codeHash") {
            // uncomment below to test the property
            //modelInstance.codeHash shouldBe ("TODO")
        }

        // to test the property `methods`
        should("test methods") {
            // uncomment below to test the property
            //modelInstance.methods shouldBe ("TODO")
        }

        // to test the property `compiler`
        should("test compiler") {
            // uncomment below to test the property
            //modelInstance.compiler shouldBe ("TODO")
        }

    }
}
