/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.BlockchainConfig43
import io.tonapi.models.SizeLimitsConfig

class BlockchainConfig43Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockchainConfig43
        //val modelInstance = BlockchainConfig43()

        // to test the property `sizeLimitsConfig`
        should("test sizeLimitsConfig") {
            // uncomment below to test the property
            //modelInstance.sizeLimitsConfig shouldBe ("TODO")
        }

    }
}
