/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.BlockchainConfig5

class BlockchainConfig5Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockchainConfig5
        //val modelInstance = BlockchainConfig5()

        // to test the property `feeBurnNom`
        should("test feeBurnNom") {
            // uncomment below to test the property
            //modelInstance.feeBurnNom shouldBe ("TODO")
        }

        // to test the property `feeBurnDenom`
        should("test feeBurnDenom") {
            // uncomment below to test the property
            //modelInstance.feeBurnDenom shouldBe ("TODO")
        }

        // to test the property `blackholeAddr`
        should("test blackholeAddr") {
            // uncomment below to test the property
            //modelInstance.blackholeAddr shouldBe ("TODO")
        }

    }
}
