/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.BlockchainConfig79
import io.tonapi.models.JettonBridgeParams

class BlockchainConfig79Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockchainConfig79
        //val modelInstance = BlockchainConfig79()

        // to test the property `jettonBridgeParams`
        should("test jettonBridgeParams") {
            // uncomment below to test the property
            //modelInstance.jettonBridgeParams shouldBe ("TODO")
        }

    }
}
