/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.BouncePhaseType

class BouncePhaseTypeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BouncePhaseType
        //val modelInstance = BouncePhaseType()

    }
}
