/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.DecodedMessageExtInMsgDecoded
import io.tonapi.models.DecodedMessageExtInMsgDecodedWalletHighloadV2
import io.tonapi.models.DecodedMessageExtInMsgDecodedWalletV3
import io.tonapi.models.DecodedMessageExtInMsgDecodedWalletV4

class DecodedMessageExtInMsgDecodedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DecodedMessageExtInMsgDecoded
        //val modelInstance = DecodedMessageExtInMsgDecoded()

        // to test the property `walletV3`
        should("test walletV3") {
            // uncomment below to test the property
            //modelInstance.walletV3 shouldBe ("TODO")
        }

        // to test the property `walletV4`
        should("test walletV4") {
            // uncomment below to test the property
            //modelInstance.walletV4 shouldBe ("TODO")
        }

        // to test the property `walletHighloadV2`
        should("test walletHighloadV2") {
            // uncomment below to test the property
            //modelInstance.walletHighloadV2 shouldBe ("TODO")
        }

    }
}
