/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.DomainBid
import io.tonapi.models.AccountAddress

class DomainBidTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DomainBid
        //val modelInstance = DomainBid()

        // to test the property `success`
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `txTime`
        should("test txTime") {
            // uncomment below to test the property
            //modelInstance.txTime shouldBe ("TODO")
        }

        // to test the property `txHash`
        should("test txHash") {
            // uncomment below to test the property
            //modelInstance.txHash shouldBe ("TODO")
        }

        // to test the property `bidder`
        should("test bidder") {
            // uncomment below to test the property
            //modelInstance.bidder shouldBe ("TODO")
        }

    }
}
