/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.ElectionsDepositStakeAction
import io.tonapi.models.AccountAddress

class ElectionsDepositStakeActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ElectionsDepositStakeAction
        //val modelInstance = ElectionsDepositStakeAction()

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `staker`
        should("test staker") {
            // uncomment below to test the property
            //modelInstance.staker shouldBe ("TODO")
        }

    }
}
