/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.EmulateMessageToWalletRequest
import io.tonapi.models.EmulateMessageToWalletRequestParamsInner

class EmulateMessageToWalletRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmulateMessageToWalletRequest
        //val modelInstance = EmulateMessageToWalletRequest()

        // to test the property `boc`
        should("test boc") {
            // uncomment below to test the property
            //modelInstance.boc shouldBe ("TODO")
        }

        // to test the property `params` - additional per account configuration
        should("test params") {
            // uncomment below to test the property
            //modelInstance.params shouldBe ("TODO")
        }

    }
}
