/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.GetAccountDiff200Response

class GetAccountDiff200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAccountDiff200Response
        //val modelInstance = GetAccountDiff200Response()

        // to test the property `balanceChange`
        should("test balanceChange") {
            // uncomment below to test the property
            //modelInstance.balanceChange shouldBe ("TODO")
        }

    }
}
