/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward
import io.tonapi.models.BlockRaw
import io.tonapi.models.GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures

class GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward
        //val modelInstance = GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward()

        // to test the property `toKeyBlock`
        should("test toKeyBlock") {
            // uncomment below to test the property
            //modelInstance.toKeyBlock shouldBe ("TODO")
        }

        // to test the property `from`
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `to`
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `destProof`
        should("test destProof") {
            // uncomment below to test the property
            //modelInstance.destProof shouldBe ("TODO")
        }

        // to test the property `configProof`
        should("test configProof") {
            // uncomment below to test the property
            //modelInstance.configProof shouldBe ("TODO")
        }

        // to test the property `signatures`
        should("test signatures") {
            // uncomment below to test the property
            //modelInstance.signatures shouldBe ("TODO")
        }

    }
}
