/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.GetRawConfig200Response
import io.tonapi.models.BlockRaw

class GetRawConfig200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetRawConfig200Response
        //val modelInstance = GetRawConfig200Response()

        // to test the property `mode`
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `stateProof`
        should("test stateProof") {
            // uncomment below to test the property
            //modelInstance.stateProof shouldBe ("TODO")
        }

        // to test the property `configProof`
        should("test configProof") {
            // uncomment below to test the property
            //modelInstance.configProof shouldBe ("TODO")
        }

    }
}
