/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner

class GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner
        //val modelInstance = GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner()

        // to test the property `nodeIdShort`
        should("test nodeIdShort") {
            // uncomment below to test the property
            //modelInstance.nodeIdShort shouldBe ("TODO")
        }

        // to test the property `signature`
        should("test signature") {
            // uncomment below to test the property
            //modelInstance.signature shouldBe ("TODO")
        }

    }
}
