/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.GetStorageProviders200Response
import io.tonapi.models.StorageProvider

class GetStorageProviders200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStorageProviders200Response
        //val modelInstance = GetStorageProviders200Response()

        // to test the property `providers`
        should("test providers") {
            // uncomment below to test the property
            //modelInstance.providers shouldBe ("TODO")
        }

    }
}
