/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.GetTonConnectPayload200Response

class GetTonConnectPayload200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTonConnectPayload200Response
        //val modelInstance = GetTonConnectPayload200Response()

        // to test the property `payload`
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

    }
}
