/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.JettonHolders
import io.tonapi.models.JettonHoldersAddressesInner

class JettonHoldersTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JettonHolders
        //val modelInstance = JettonHolders()

        // to test the property `addresses`
        should("test addresses") {
            // uncomment below to test the property
            //modelInstance.addresses shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
