/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.JettonBridgePrices

class JettonBridgePricesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JettonBridgePrices
        //val modelInstance = JettonBridgePrices()

        // to test the property `bridgeBurnFee`
        should("test bridgeBurnFee") {
            // uncomment below to test the property
            //modelInstance.bridgeBurnFee shouldBe ("TODO")
        }

        // to test the property `bridgeMintFee`
        should("test bridgeMintFee") {
            // uncomment below to test the property
            //modelInstance.bridgeMintFee shouldBe ("TODO")
        }

        // to test the property `walletMinTonsForStorage`
        should("test walletMinTonsForStorage") {
            // uncomment below to test the property
            //modelInstance.walletMinTonsForStorage shouldBe ("TODO")
        }

        // to test the property `walletGasConsumption`
        should("test walletGasConsumption") {
            // uncomment below to test the property
            //modelInstance.walletGasConsumption shouldBe ("TODO")
        }

        // to test the property `minterMinTonsForStorage`
        should("test minterMinTonsForStorage") {
            // uncomment below to test the property
            //modelInstance.minterMinTonsForStorage shouldBe ("TODO")
        }

        // to test the property `discoverGasConsumption`
        should("test discoverGasConsumption") {
            // uncomment below to test the property
            //modelInstance.discoverGasConsumption shouldBe ("TODO")
        }

    }
}
