/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.MethodExecutionResult
import io.tonapi.models.TvmStackRecord

class MethodExecutionResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MethodExecutionResult
        //val modelInstance = MethodExecutionResult()

        // to test the property `success`
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `exitCode` - tvm exit code
        should("test exitCode") {
            // uncomment below to test the property
            //modelInstance.exitCode shouldBe ("TODO")
        }

        // to test the property `stack`
        should("test stack") {
            // uncomment below to test the property
            //modelInstance.stack shouldBe ("TODO")
        }

        // to test the property `decoded`
        should("test decoded") {
            // uncomment below to test the property
            //modelInstance.decoded shouldBe ("TODO")
        }

    }
}
