/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.NftCollections
import io.tonapi.models.NftCollection

class NftCollectionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NftCollections
        //val modelInstance = NftCollections()

        // to test the property `nftCollections`
        should("test nftCollections") {
            // uncomment below to test the property
            //modelInstance.nftCollections shouldBe ("TODO")
        }

    }
}
