/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.Oracle

class OracleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Oracle
        //val modelInstance = Oracle()

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `secpPubkey`
        should("test secpPubkey") {
            // uncomment below to test the property
            //modelInstance.secpPubkey shouldBe ("TODO")
        }

    }
}
