/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.Risk
import io.tonapi.models.JettonQuantity
import io.tonapi.models.NftItem

class RiskTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Risk
        //val modelInstance = Risk()

        // to test the property `transferAllRemainingBalance` - transfer all the remaining balance of the wallet.
        should("test transferAllRemainingBalance") {
            // uncomment below to test the property
            //modelInstance.transferAllRemainingBalance shouldBe ("TODO")
        }

        // to test the property `ton`
        should("test ton") {
            // uncomment below to test the property
            //modelInstance.ton shouldBe ("TODO")
        }

        // to test the property `jettons`
        should("test jettons") {
            // uncomment below to test the property
            //modelInstance.jettons shouldBe ("TODO")
        }

        // to test the property `nfts`
        should("test nfts") {
            // uncomment below to test the property
            //modelInstance.nfts shouldBe ("TODO")
        }

    }
}
