/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.SmartContractAction
import io.tonapi.models.AccountAddress
import io.tonapi.models.Refund

class SmartContractActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SmartContractAction
        //val modelInstance = SmartContractAction()

        // to test the property `executor`
        should("test executor") {
            // uncomment below to test the property
            //modelInstance.executor shouldBe ("TODO")
        }

        // to test the property ``contract``
        should("test `contract`") {
            // uncomment below to test the property
            //modelInstance.`contract` shouldBe ("TODO")
        }

        // to test the property `tonAttached` - amount in nanotons
        should("test tonAttached") {
            // uncomment below to test the property
            //modelInstance.tonAttached shouldBe ("TODO")
        }

        // to test the property `operation`
        should("test operation") {
            // uncomment below to test the property
            //modelInstance.operation shouldBe ("TODO")
        }

        // to test the property `payload`
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

        // to test the property `refund`
        should("test refund") {
            // uncomment below to test the property
            //modelInstance.refund shouldBe ("TODO")
        }

    }
}
