/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.SubscriptionAction
import io.tonapi.models.AccountAddress

class SubscriptionActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubscriptionAction
        //val modelInstance = SubscriptionAction()

        // to test the property `subscriber`
        should("test subscriber") {
            // uncomment below to test the property
            //modelInstance.subscriber shouldBe ("TODO")
        }

        // to test the property `subscription`
        should("test subscription") {
            // uncomment below to test the property
            //modelInstance.subscription shouldBe ("TODO")
        }

        // to test the property `beneficiary`
        should("test beneficiary") {
            // uncomment below to test the property
            //modelInstance.beneficiary shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `initial`
        should("test initial") {
            // uncomment below to test the property
            //modelInstance.initial shouldBe ("TODO")
        }

    }
}
