/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.Subscription

class SubscriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Subscription
        //val modelInstance = Subscription()

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `walletAddress`
        should("test walletAddress") {
            // uncomment below to test the property
            //modelInstance.walletAddress shouldBe ("TODO")
        }

        // to test the property `beneficiaryAddress`
        should("test beneficiaryAddress") {
            // uncomment below to test the property
            //modelInstance.beneficiaryAddress shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

        // to test the property `startTime`
        should("test startTime") {
            // uncomment below to test the property
            //modelInstance.startTime shouldBe ("TODO")
        }

        // to test the property `timeout`
        should("test timeout") {
            // uncomment below to test the property
            //modelInstance.timeout shouldBe ("TODO")
        }

        // to test the property `lastPaymentTime`
        should("test lastPaymentTime") {
            // uncomment below to test the property
            //modelInstance.lastPaymentTime shouldBe ("TODO")
        }

        // to test the property `lastRequestTime`
        should("test lastRequestTime") {
            // uncomment below to test the property
            //modelInstance.lastRequestTime shouldBe ("TODO")
        }

        // to test the property `subscriptionId`
        should("test subscriptionId") {
            // uncomment below to test the property
            //modelInstance.subscriptionId shouldBe ("TODO")
        }

        // to test the property `failedAttempts`
        should("test failedAttempts") {
            // uncomment below to test the property
            //modelInstance.failedAttempts shouldBe ("TODO")
        }

    }
}
