/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.TokenRates

class TokenRatesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TokenRates
        //val modelInstance = TokenRates()

        // to test the property `prices`
        should("test prices") {
            // uncomment below to test the property
            //modelInstance.prices shouldBe ("TODO")
        }

        // to test the property `diff24h`
        should("test diff24h") {
            // uncomment below to test the property
            //modelInstance.diff24h shouldBe ("TODO")
        }

        // to test the property `diff7d`
        should("test diff7d") {
            // uncomment below to test the property
            //modelInstance.diff7d shouldBe ("TODO")
        }

        // to test the property `diff30d`
        should("test diff30d") {
            // uncomment below to test the property
            //modelInstance.diff30d shouldBe ("TODO")
        }

    }
}
