/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.TonConnectProofRequestProofDomain

class TonConnectProofRequestProofDomainTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TonConnectProofRequestProofDomain
        //val modelInstance = TonConnectProofRequestProofDomain()

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `lengthBytes`
        should("test lengthBytes") {
            // uncomment below to test the property
            //modelInstance.lengthBytes shouldBe ("TODO")
        }

    }
}
