/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.TraceID

class TraceIDTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TraceID
        //val modelInstance = TraceID()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `utime`
        should("test utime") {
            // uncomment below to test the property
            //modelInstance.utime shouldBe ("TODO")
        }

    }
}
