/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.tonapi.models.Validators
import io.tonapi.models.Validator

class ValidatorsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Validators
        //val modelInstance = Validators()

        // to test the property `electAt`
        should("test electAt") {
            // uncomment below to test the property
            //modelInstance.electAt shouldBe ("TODO")
        }

        // to test the property `electClose`
        should("test electClose") {
            // uncomment below to test the property
            //modelInstance.electClose shouldBe ("TODO")
        }

        // to test the property `minStake`
        should("test minStake") {
            // uncomment below to test the property
            //modelInstance.minStake shouldBe ("TODO")
        }

        // to test the property `totalStake`
        should("test totalStake") {
            // uncomment below to test the property
            //modelInstance.totalStake shouldBe ("TODO")
        }

        // to test the property `validators`
        should("test validators") {
            // uncomment below to test the property
            //modelInstance.validators shouldBe ("TODO")
        }

    }
}
