/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.models.BlockSchema

class BlockSchemaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockSchema
        //val modelInstance = BlockSchema()

        // to test the property `blockNumber`
        should("test blockNumber") {
            // uncomment below to test the property
            //modelInstance.blockNumber shouldBe ("TODO")
        }

        // to test the property `blockTimestamp`
        should("test blockTimestamp") {
            // uncomment below to test the property
            //modelInstance.blockTimestamp shouldBe ("TODO")
        }

    }
}
