/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.models.GetAssetList200Response
import io.stonfiapi.models.AssetInfoSchema

class GetAssetList200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAssetList200Response
        //val modelInstance = GetAssetList200Response()

        // to test the property `assetList`
        should("test assetList") {
            // uncomment below to test the property
            //modelInstance.assetList shouldBe ("TODO")
        }

    }
}
