/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.models.GetFarmList200Response
import io.stonfiapi.models.FarmInfoSchema

class GetFarmList200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFarmList200Response
        //val modelInstance = GetFarmList200Response()

        // to test the property `farmList`
        should("test farmList") {
            // uncomment below to test the property
            //modelInstance.farmList shouldBe ("TODO")
        }

    }
}
