/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.models.OperationStatus

class OperationStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OperationStatus
        //val modelInstance = OperationStatus()

        // to test the property `address` - Wallet address
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `balanceDeltas` - Changes in balance
        should("test balanceDeltas") {
            // uncomment below to test the property
            //modelInstance.balanceDeltas shouldBe ("TODO")
        }

        // to test the property `coins` - Transaction coins
        should("test coins") {
            // uncomment below to test the property
            //modelInstance.coins shouldBe ("TODO")
        }

        // to test the property `exitCode` - Exit code of operation
        should("test exitCode") {
            // uncomment below to test the property
            //modelInstance.exitCode shouldBe ("TODO")
        }

        // to test the property `logicalTime` - Operation logical time
        should("test logicalTime") {
            // uncomment below to test the property
            //modelInstance.logicalTime shouldBe ("TODO")
        }

        // to test the property `queryId` - Id of operation status query
        should("test queryId") {
            // uncomment below to test the property
            //modelInstance.queryId shouldBe ("TODO")
        }

        // to test the property `txHash` - Operation hash
        should("test txHash") {
            // uncomment below to test the property
            //modelInstance.txHash shouldBe ("TODO")
        }

    }
}
