/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.models.OperationsInfo
import io.stonfiapi.models.AssetInfoSchema
import io.stonfiapi.models.OperationStat

class OperationsInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OperationsInfo
        //val modelInstance = OperationsInfo()

        // to test the property `asset0Info`
        should("test asset0Info") {
            // uncomment below to test the property
            //modelInstance.asset0Info shouldBe ("TODO")
        }

        // to test the property `asset1Info`
        should("test asset1Info") {
            // uncomment below to test the property
            //modelInstance.asset1Info shouldBe ("TODO")
        }

        // to test the property `operation`
        should("test operation") {
            // uncomment below to test the property
            //modelInstance.operation shouldBe ("TODO")
        }

    }
}
