/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.models.PoolInfoSchema

class PoolInfoSchemaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PoolInfoSchema
        //val modelInstance = PoolInfoSchema()

        // to test the property `address` - Address of pool
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `collectedToken0ProtocolFee` - Protocol fee collected in token0
        should("test collectedToken0ProtocolFee") {
            // uncomment below to test the property
            //modelInstance.collectedToken0ProtocolFee shouldBe ("TODO")
        }

        // to test the property `collectedToken1ProtocolFee` - Protocol fee collected in token1
        should("test collectedToken1ProtocolFee") {
            // uncomment below to test the property
            //modelInstance.collectedToken1ProtocolFee shouldBe ("TODO")
        }

        // to test the property `deprecated` - Pool is deprecated
        should("test deprecated") {
            // uncomment below to test the property
            //modelInstance.deprecated shouldBe ("TODO")
        }

        // to test the property `lpFee` - Fee of liquidity pool token
        should("test lpFee") {
            // uncomment below to test the property
            //modelInstance.lpFee shouldBe ("TODO")
        }

        // to test the property `lpTotalSupply` - Total supply of liquidity pool tokens
        should("test lpTotalSupply") {
            // uncomment below to test the property
            //modelInstance.lpTotalSupply shouldBe ("TODO")
        }

        // to test the property `protocolFee` - Fee of protocol
        should("test protocolFee") {
            // uncomment below to test the property
            //modelInstance.protocolFee shouldBe ("TODO")
        }

        // to test the property `protocolFeeAddress` - Address of protocol fee
        should("test protocolFeeAddress") {
            // uncomment below to test the property
            //modelInstance.protocolFeeAddress shouldBe ("TODO")
        }

        // to test the property `refFee` - Referral fee
        should("test refFee") {
            // uncomment below to test the property
            //modelInstance.refFee shouldBe ("TODO")
        }

        // to test the property `reserve0` - Reserve of token0 in pool
        should("test reserve0") {
            // uncomment below to test the property
            //modelInstance.reserve0 shouldBe ("TODO")
        }

        // to test the property `reserve1` - Reserve of token1 in pool
        should("test reserve1") {
            // uncomment below to test the property
            //modelInstance.reserve1 shouldBe ("TODO")
        }

        // to test the property `routerAddress` - Address of router
        should("test routerAddress") {
            // uncomment below to test the property
            //modelInstance.routerAddress shouldBe ("TODO")
        }

        // to test the property `token0Address` - Address of token0
        should("test token0Address") {
            // uncomment below to test the property
            //modelInstance.token0Address shouldBe ("TODO")
        }

        // to test the property `token1Address` - Address of token1
        should("test token1Address") {
            // uncomment below to test the property
            //modelInstance.token1Address shouldBe ("TODO")
        }

        // to test the property `apy1d` - Annual percentage yield on the last day
        should("test apy1d") {
            // uncomment below to test the property
            //modelInstance.apy1d shouldBe ("TODO")
        }

        // to test the property `apy30d` - Annual percentage yield on the last month
        should("test apy30d") {
            // uncomment below to test the property
            //modelInstance.apy30d shouldBe ("TODO")
        }

        // to test the property `apy7d` - Annual percentage yield on the last week
        should("test apy7d") {
            // uncomment below to test the property
            //modelInstance.apy7d shouldBe ("TODO")
        }

        // to test the property `lpAccountAddress` - Account address of liquidity pool tokens
        should("test lpAccountAddress") {
            // uncomment below to test the property
            //modelInstance.lpAccountAddress shouldBe ("TODO")
        }

        // to test the property `lpBalance` - Balance of liquidity pool tokens
        should("test lpBalance") {
            // uncomment below to test the property
            //modelInstance.lpBalance shouldBe ("TODO")
        }

        // to test the property `lpPriceUsd` - Price of liquidity pool token in USD
        should("test lpPriceUsd") {
            // uncomment below to test the property
            //modelInstance.lpPriceUsd shouldBe ("TODO")
        }

        // to test the property `lpTotalSupplyUsd` - Total supply of liquidity pool tokens in USD
        should("test lpTotalSupplyUsd") {
            // uncomment below to test the property
            //modelInstance.lpTotalSupplyUsd shouldBe ("TODO")
        }

        // to test the property `lpWalletAddress` - Wallet address of liquidity pool tokens
        should("test lpWalletAddress") {
            // uncomment below to test the property
            //modelInstance.lpWalletAddress shouldBe ("TODO")
        }

        // to test the property `token0Balance` - Balance of token0
        should("test token0Balance") {
            // uncomment below to test the property
            //modelInstance.token0Balance shouldBe ("TODO")
        }

        // to test the property `token1Balance` - Balance of token1
        should("test token1Balance") {
            // uncomment below to test the property
            //modelInstance.token1Balance shouldBe ("TODO")
        }

    }
}
