/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.stonfiapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.stonfiapi.models.ScreenerAssetInfo200Response
import io.stonfiapi.models.AssetInfoScreenerSchema

class ScreenerAssetInfo200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScreenerAssetInfo200Response
        //val modelInstance = ScreenerAssetInfo200Response()

        // to test the property `asset`
        should("test asset") {
            // uncomment below to test the property
            //modelInstance.asset shouldBe ("TODO")
        }

    }
}
