/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.exchangeapi.models.CalculateSwap400Response
import io.exchangeapi.models.CreateOfframpOrderRequest
import io.exchangeapi.models.ExchangePaymentMethodType
import io.exchangeapi.models.GetCrossSwapAsset404Response
import io.exchangeapi.models.Healthcheck500Response
import io.exchangeapi.models.OfframpAssetDetail
import io.exchangeapi.models.OfframpConfiguration
import io.exchangeapi.models.OfframpOrder
import io.exchangeapi.models.OfframpQuoteRequest
import io.exchangeapi.models.OfframpQuotes
import io.exchangeapi.models.Platform

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import io.infrastructure.ApiClient
import io.infrastructure.ApiResponse
import io.infrastructure.ClientException
import io.infrastructure.ClientError
import io.infrastructure.ServerException
import io.infrastructure.ServerError
import io.infrastructure.MultiValueMap
import io.infrastructure.PartConfig
import io.infrastructure.RequestConfig
import io.infrastructure.RequestMethod
import io.infrastructure.ResponseType
import io.infrastructure.Success
import io.infrastructure.toMultiValue

class OfframpApi(basePath: String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createOfframpOrder(createOfframpOrderRequest: CreateOfframpOrderRequest, F: String? = null, deviceCountryCode: String? = null, storeCountryCode: String? = null, simCountry: String? = null, timezone: String? = null, isVpnActive: Boolean? = null, build: String? = null, platform: Platform? = null, idempotencyKey: java.util.UUID? = null): OfframpOrder {
        val localVarResponse = createOfframpOrderWithHttpInfo(createOfframpOrderRequest = createOfframpOrderRequest, F = F, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform, idempotencyKey = idempotencyKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OfframpOrder
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createOfframpOrderWithHttpInfo(createOfframpOrderRequest: CreateOfframpOrderRequest, F: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?, idempotencyKey: java.util.UUID?): ApiResponse<OfframpOrder?> {
        val localVariableConfig = createOfframpOrderRequestConfig(createOfframpOrderRequest = createOfframpOrderRequest, F = F, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform, idempotencyKey = idempotencyKey)

        return request<CreateOfframpOrderRequest, OfframpOrder>(
            localVariableConfig
        )
    }

    fun createOfframpOrderRequestConfig(createOfframpOrderRequest: CreateOfframpOrderRequest, F: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?, idempotencyKey: java.util.UUID?): RequestConfig<CreateOfframpOrderRequest> {
        val localVariableBody = createOfframpOrderRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<String, List<String>>()
            .apply {
                if (deviceCountryCode != null) {
                    put("device_country_code", listOf(deviceCountryCode.toString()))
                }
                if (storeCountryCode != null) {
                    put("store_country_code", listOf(storeCountryCode.toString()))
                }
                if (simCountry != null) {
                    put("sim_country", listOf(simCountry.toString()))
                }
                if (timezone != null) {
                    put("timezone", listOf(timezone.toString()))
                }
                if (isVpnActive != null) {
                    put("is_vpn_active", listOf(isVpnActive.toString()))
                }
                if (build != null) {
                    put("build", listOf(build.toString()))
                }
                if (platform != null) {
                    put("platform", listOf(platform.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        F?.apply { localVariableHeaders["F"] = this.toString() }
        idempotencyKey?.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/offramp/orders",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getOfframpAsset(assetId: String, F: String? = null, country: String? = null, deviceCountryCode: String? = null, storeCountryCode: String? = null, simCountry: String? = null, timezone: String? = null, isVpnActive: Boolean? = null, build: String? = null, platform: Platform? = null, lang: String? = null): OfframpAssetDetail {
        val localVarResponse = getOfframpAssetWithHttpInfo(assetId = assetId, F = F, country = country, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform, lang = lang)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OfframpAssetDetail
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getOfframpAssetWithHttpInfo(assetId: String, F: String?, country: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?, lang: String?): ApiResponse<OfframpAssetDetail?> {
        val localVariableConfig = getOfframpAssetRequestConfig(assetId = assetId, F = F, country = country, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform, lang = lang)

        return request<Unit, OfframpAssetDetail>(
            localVariableConfig
        )
    }

    fun getOfframpAssetRequestConfig(assetId: String, F: String?, country: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?, lang: String?): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<String, List<String>>()
            .apply {
                put("asset_id", listOf(assetId.toString()))
                if (country != null) {
                    put("country", listOf(country.toString()))
                }
                if (deviceCountryCode != null) {
                    put("device_country_code", listOf(deviceCountryCode.toString()))
                }
                if (storeCountryCode != null) {
                    put("store_country_code", listOf(storeCountryCode.toString()))
                }
                if (simCountry != null) {
                    put("sim_country", listOf(simCountry.toString()))
                }
                if (timezone != null) {
                    put("timezone", listOf(timezone.toString()))
                }
                if (isVpnActive != null) {
                    put("is_vpn_active", listOf(isVpnActive.toString()))
                }
                if (build != null) {
                    put("build", listOf(build.toString()))
                }
                if (platform != null) {
                    put("platform", listOf(platform.toString()))
                }
                if (lang != null) {
                    put("lang", listOf(lang.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        F?.apply { localVariableHeaders["F"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/offramp/asset",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getOfframpConfiguration(sourceChain: String? = null, fiat: String? = null, payoutMethod: ExchangePaymentMethodType? = null, q: String? = null, country: String? = null, deviceCountryCode: String? = null, storeCountryCode: String? = null, simCountry: String? = null, timezone: String? = null, isVpnActive: Boolean? = null, build: String? = null, platform: Platform? = null, lang: String? = null, cursor: String? = null, limit: Int? = 20, ifNoneMatch: String? = null, F: String? = null): OfframpConfiguration {
        val localVarResponse = getOfframpConfigurationWithHttpInfo(sourceChain = sourceChain, fiat = fiat, payoutMethod = payoutMethod, q = q, country = country, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform, lang = lang, cursor = cursor, limit = limit, ifNoneMatch = ifNoneMatch, F = F)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OfframpConfiguration
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getOfframpConfigurationWithHttpInfo(sourceChain: String?, fiat: String?, payoutMethod: ExchangePaymentMethodType?, q: String?, country: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?, lang: String?, cursor: String?, limit: Int?, ifNoneMatch: String?, F: String?): ApiResponse<OfframpConfiguration?> {
        val localVariableConfig = getOfframpConfigurationRequestConfig(sourceChain = sourceChain, fiat = fiat, payoutMethod = payoutMethod, q = q, country = country, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform, lang = lang, cursor = cursor, limit = limit, ifNoneMatch = ifNoneMatch, F = F)

        return request<Unit, OfframpConfiguration>(
            localVariableConfig
        )
    }

    fun getOfframpConfigurationRequestConfig(sourceChain: String?, fiat: String?, payoutMethod: ExchangePaymentMethodType?, q: String?, country: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?, lang: String?, cursor: String?, limit: Int?, ifNoneMatch: String?, F: String?): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<String, List<String>>()
            .apply {
                if (sourceChain != null) {
                    put("source_chain", listOf(sourceChain.toString()))
                }
                if (fiat != null) {
                    put("fiat", listOf(fiat.toString()))
                }
                if (payoutMethod != null) {
                    put("payout_method", listOf(payoutMethod.toString()))
                }
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
                if (country != null) {
                    put("country", listOf(country.toString()))
                }
                if (deviceCountryCode != null) {
                    put("device_country_code", listOf(deviceCountryCode.toString()))
                }
                if (storeCountryCode != null) {
                    put("store_country_code", listOf(storeCountryCode.toString()))
                }
                if (simCountry != null) {
                    put("sim_country", listOf(simCountry.toString()))
                }
                if (timezone != null) {
                    put("timezone", listOf(timezone.toString()))
                }
                if (isVpnActive != null) {
                    put("is_vpn_active", listOf(isVpnActive.toString()))
                }
                if (build != null) {
                    put("build", listOf(build.toString()))
                }
                if (platform != null) {
                    put("platform", listOf(platform.toString()))
                }
                if (lang != null) {
                    put("lang", listOf(lang.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        ifNoneMatch?.apply { localVariableHeaders["If-None-Match"] = this.toString() }
        F?.apply { localVariableHeaders["F"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/offramp/configuration",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getOfframpOrder(orderId: String): OfframpOrder {
        val localVarResponse = getOfframpOrderWithHttpInfo(orderId = orderId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OfframpOrder
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getOfframpOrderWithHttpInfo(orderId: String): ApiResponse<OfframpOrder?> {
        val localVariableConfig = getOfframpOrderRequestConfig(orderId = orderId)

        return request<Unit, OfframpOrder>(
            localVariableConfig
        )
    }

    fun getOfframpOrderRequestConfig(orderId: String): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/offramp/orders/{order_id}".replace("{"+"order_id"+"}", encodeURIComponent(orderId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun offrampQuote(offrampQuoteRequest: OfframpQuoteRequest, F: String? = null, deviceCountryCode: String? = null, storeCountryCode: String? = null, simCountry: String? = null, timezone: String? = null, isVpnActive: Boolean? = null, build: String? = null, platform: Platform? = null): OfframpQuotes {
        val localVarResponse = offrampQuoteWithHttpInfo(offrampQuoteRequest = offrampQuoteRequest, F = F, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OfframpQuotes
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun offrampQuoteWithHttpInfo(offrampQuoteRequest: OfframpQuoteRequest, F: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?): ApiResponse<OfframpQuotes?> {
        val localVariableConfig = offrampQuoteRequestConfig(offrampQuoteRequest = offrampQuoteRequest, F = F, deviceCountryCode = deviceCountryCode, storeCountryCode = storeCountryCode, simCountry = simCountry, timezone = timezone, isVpnActive = isVpnActive, build = build, platform = platform)

        return request<OfframpQuoteRequest, OfframpQuotes>(
            localVariableConfig
        )
    }

    fun offrampQuoteRequestConfig(offrampQuoteRequest: OfframpQuoteRequest, F: String?, deviceCountryCode: String?, storeCountryCode: String?, simCountry: String?, timezone: String?, isVpnActive: Boolean?, build: String?, platform: Platform?): RequestConfig<OfframpQuoteRequest> {
        val localVariableBody = offrampQuoteRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<String, List<String>>()
            .apply {
                if (deviceCountryCode != null) {
                    put("device_country_code", listOf(deviceCountryCode.toString()))
                }
                if (storeCountryCode != null) {
                    put("store_country_code", listOf(storeCountryCode.toString()))
                }
                if (simCountry != null) {
                    put("sim_country", listOf(simCountry.toString()))
                }
                if (timezone != null) {
                    put("timezone", listOf(timezone.toString()))
                }
                if (isVpnActive != null) {
                    put("is_vpn_active", listOf(isVpnActive.toString()))
                }
                if (build != null) {
                    put("build", listOf(build.toString()))
                }
                if (platform != null) {
                    put("platform", listOf(platform.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        F?.apply { localVariableHeaders["F"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/offramp/quote",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    private fun encodeURIComponent(uriComponent: String): String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
