/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.kandelabrapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class GetCandlesResponse(
    /* Ticker symbol */
    @SerialName(value = "ticker")
    val ticker: String,

    /* Candle resolution */
    @SerialName(value = "resolution")
    val resolution: String,

    /* Start timestamp in milliseconds */
    @SerialName(value = "start_ts")
    val startTs: Long,
    @SerialName(value = "candles")
    val candles: List<Candle>
) {
}

