/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param address 
 * @param isScam Is this account was marked as part of scammers activity
 * @param isWallet 
 * @param name Display name. Data collected from different sources like moderation lists, dns, collections names and over.
 * @param icon 
 */


data class AccountAddress (

    @Json(name = "address")
    val address: kotlin.String,

    /* Is this account was marked as part of scammers activity */
    @Json(name = "is_scam")
    val isScam: kotlin.Boolean,

    @Json(name = "is_wallet")
    val isWallet: kotlin.Boolean,

    /* Display name. Data collected from different sources like moderation lists, dns, collections names and over. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null

)

