/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param underload 
 * @param softLimit 
 * @param hardLimit 
 */


data class BlockParamLimits (

    @Json(name = "underload")
    val underload: kotlin.Long,

    @Json(name = "soft_limit")
    val softLimit: kotlin.Long,

    @Json(name = "hard_limit")
    val hardLimit: kotlin.Long

)

