/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param workchainId 
 * @param shard 
 * @param seqno 
 * @param rootHash 
 * @param fileHash 
 * @param globalId 
 * @param version 
 * @param afterMerge 
 * @param beforeSplit 
 * @param afterSplit 
 * @param wantSplit 
 * @param wantMerge 
 * @param keyBlock 
 * @param genUtime 
 * @param startLt 
 * @param endLt 
 * @param vertSeqno 
 * @param genCatchainSeqno 
 * @param minRefMcSeqno 
 * @param prevKeyBlockSeqno 
 * @param prevRefs 
 * @param inMsgDescrLength 
 * @param outMsgDescrLength 
 * @param randSeed 
 * @param createdBy 
 * @param genSoftwareVersion 
 * @param genSoftwareCapabilities 
 * @param masterRef 
 */


data class BlockchainBlock (

    @Json(name = "workchain_id")
    val workchainId: kotlin.Int,

    @Json(name = "shard")
    val shard: kotlin.String,

    @Json(name = "seqno")
    val seqno: kotlin.Int,

    @Json(name = "root_hash")
    val rootHash: kotlin.String,

    @Json(name = "file_hash")
    val fileHash: kotlin.String,

    @Json(name = "global_id")
    val globalId: kotlin.Int,

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "after_merge")
    val afterMerge: kotlin.Boolean,

    @Json(name = "before_split")
    val beforeSplit: kotlin.Boolean,

    @Json(name = "after_split")
    val afterSplit: kotlin.Boolean,

    @Json(name = "want_split")
    val wantSplit: kotlin.Boolean,

    @Json(name = "want_merge")
    val wantMerge: kotlin.Boolean,

    @Json(name = "key_block")
    val keyBlock: kotlin.Boolean,

    @Json(name = "gen_utime")
    val genUtime: kotlin.Long,

    @Json(name = "start_lt")
    val startLt: kotlin.Long,

    @Json(name = "end_lt")
    val endLt: kotlin.Long,

    @Json(name = "vert_seqno")
    val vertSeqno: kotlin.Int,

    @Json(name = "gen_catchain_seqno")
    val genCatchainSeqno: kotlin.Int,

    @Json(name = "min_ref_mc_seqno")
    val minRefMcSeqno: kotlin.Int,

    @Json(name = "prev_key_block_seqno")
    val prevKeyBlockSeqno: kotlin.Int,

    @Json(name = "prev_refs")
    val prevRefs: kotlin.collections.List<kotlin.String>,

    @Json(name = "in_msg_descr_length")
    val inMsgDescrLength: kotlin.Long,

    @Json(name = "out_msg_descr_length")
    val outMsgDescrLength: kotlin.Long,

    @Json(name = "rand_seed")
    val randSeed: kotlin.String,

    @Json(name = "created_by")
    val createdBy: kotlin.String,

    @Json(name = "gen_software_version")
    val genSoftwareVersion: kotlin.Int? = null,

    @Json(name = "gen_software_capabilities")
    val genSoftwareCapabilities: kotlin.Long? = null,

    @Json(name = "master_ref")
    val masterRef: kotlin.String? = null

)

