/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param boc 
 * @param decodedOpName 
 * @param opCode 
 * @param decodedBody 
 */


data class DecodedRawMessageMessage (

    @Json(name = "boc")
    val boc: kotlin.String,

    @Json(name = "decoded_op_name")
    val decodedOpName: kotlin.String? = null,

    @Json(name = "op_code")
    val opCode: kotlin.String? = null,

    @Json(name = "decoded_body")
    val decodedBody: kotlin.Any? = null

)

