/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment 
 * @param destination 
 */


data class GetInscriptionOpTemplate200Response (

    @Json(name = "comment")
    val comment: kotlin.String,

    @Json(name = "destination")
    val destination: kotlin.String

)

