/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.GetOutMsgQueueSizes200ResponseShardsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param extMsgQueueSizeLimit 
 * @param shards 
 */


data class GetOutMsgQueueSizes200Response (

    @Json(name = "ext_msg_queue_size_limit")
    val extMsgQueueSizeLimit: kotlin.Int,

    @Json(name = "shards")
    val shards: kotlin.collections.List<GetOutMsgQueueSizes200ResponseShardsInner>

)

