/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw
import io.tonapi.models.GetRawListBlockTransactions200ResponseIdsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param reqCount 
 * @param incomplete 
 * @param ids 
 * @param proof 
 */


data class GetRawListBlockTransactions200Response (

    @Json(name = "id")
    val id: BlockRaw,

    @Json(name = "req_count")
    val reqCount: kotlin.Int,

    @Json(name = "incomplete")
    val incomplete: kotlin.Boolean,

    @Json(name = "ids")
    val ids: kotlin.collections.List<GetRawListBlockTransactions200ResponseIdsInner>,

    @Json(name = "proof")
    val proof: kotlin.String

)

