/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.EncryptedComment
import io.tonapi.models.JettonPreview
import io.tonapi.models.Refund

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sendersWallet 
 * @param recipientsWallet 
 * @param amount amount in quanta of tokens
 * @param jetton 
 * @param sender 
 * @param recipient 
 * @param comment 
 * @param encryptedComment 
 * @param refund 
 */


data class JettonTransferAction (

    @Json(name = "senders_wallet")
    val sendersWallet: kotlin.String,

    @Json(name = "recipients_wallet")
    val recipientsWallet: kotlin.String,

    /* amount in quanta of tokens */
    @Json(name = "amount")
    val amount: kotlin.String,

    @Json(name = "jetton")
    val jetton: JettonPreview,

    @Json(name = "sender")
    val sender: AccountAddress? = null,

    @Json(name = "recipient")
    val recipient: AccountAddress? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "encrypted_comment")
    val encryptedComment: EncryptedComment? = null,

    @Json(name = "refund")
    val refund: Refund? = null

)

