/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.ImagePreview

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param address 
 * @param nextItemIndex 
 * @param rawCollectionContent 
 * @param approvedBy 
 * @param owner 
 * @param metadata 
 * @param previews 
 */


data class NftCollection (

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "next_item_index")
    val nextItemIndex: kotlin.Long,

    @Json(name = "raw_collection_content")
    val rawCollectionContent: kotlin.String,

    @Json(name = "approved_by")
    val approvedBy: kotlin.collections.List<NftCollection.ApprovedBy>,

    @Json(name = "owner")
    val owner: AccountAddress? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "previews")
    val previews: kotlin.collections.List<ImagePreview>? = null

) {

    /**
     * 
     *
     * Values: getgems,tonkeeper,tonPeriodDiamonds
     */
    @JsonClass(generateAdapter = false)
    enum class ApprovedBy(val value: kotlin.String) {
        @Json(name = "getgems") getgems("getgems"),
        @Json(name = "tonkeeper") tonkeeper("tonkeeper"),
        @Json(name = "ton.diamonds") tonPeriodDiamonds("ton.diamonds");
    }
}

