/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param boc 
 * @param batch 
 */


data class SendBlockchainMessageRequest (

    @Json(name = "boc")
    val boc: kotlin.String? = null,

    @Json(name = "batch")
    val batch: kotlin.collections.List<kotlin.String>? = null

)

