/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param restOnline 
 * @param indexingLatency 
 */


data class ServiceStatus (

    @Json(name = "rest_online")
    val restOnline: kotlin.Boolean = true,

    @Json(name = "indexing_latency")
    val indexingLatency: kotlin.Int

)

