/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param address 
 * @param adnlAddress 
 * @param stake 
 * @param maxFactor 
 */


data class Validator (

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "adnl_address")
    val adnlAddress: kotlin.String,

    @Json(name = "stake")
    val stake: kotlin.Long,

    @Json(name = "max_factor")
    val maxFactor: kotlin.Long

)

