/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.ValueFlowJettonsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param account 
 * @param ton 
 * @param fees 
 * @param jettons 
 */


data class ValueFlow (

    @Json(name = "account")
    val account: AccountAddress,

    @Json(name = "ton")
    val ton: kotlin.Long,

    @Json(name = "fees")
    val fees: kotlin.Long,

    @Json(name = "jettons")
    val jettons: kotlin.collections.List<ValueFlowJettonsInner>? = null

)

