/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.JettonPreview

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param account 
 * @param jetton 
 * @param quantity 
 */


data class ValueFlowJettonsInner (

    @Json(name = "account")
    val account: AccountAddress,

    @Json(name = "jetton")
    val jetton: JettonPreview,

    @Json(name = "quantity")
    val quantity: kotlin.Long

)

