/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.batteryapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class BatteryTransferRequest(
    /* Amount in TON (not nano) */
    @SerialName(value = "amount")
    val amount: String,

    /* Optional text comment for TON transfer */
    @SerialName(value = "comment")
    val comment: String? = null
) {
}

