/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.batteryapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class ConfigMeanPrices(
    @SerialName(value = "battery_mean_price_swap")
    val batteryMeanPriceSwap: Int,
    @SerialName(value = "battery_mean_price_jetton")
    val batteryMeanPriceJetton: Int,
    @SerialName(value = "battery_mean_price_nft")
    val batteryMeanPriceNft: Int,
    @SerialName(value = "battery_mean_price_tron_usdt")
    val batteryMeanPriceTronUsdt: Int? = null,
    @SerialName(value = "ton_mean_price_tron_usdt")
    val tonMeanPriceTronUsdt: Float? = null
) {
}

