/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.batteryapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class EstimateGaslessJettonTransferRequest(
    /* Jetton master address */
    @SerialName(value = "jetton_master")
    val jettonMaster: String,

    /* Destination wallet address */
    @SerialName(value = "destination")
    val destination: String,

    /* Optional response/excess address */
    @SerialName(value = "response_destination")
    val responseDestination: String? = null,

    /* Optional attached TON amount in nanoTONs */
    @SerialName(value = "attached_ton")
    val attachedTon: String? = null,

    /* Optional forward TON amount in nanoTONs */
    @SerialName(value = "forward_ton_amount")
    val forwardTonAmount: String? = null
) {
}

