/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.batteryapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class PackageItem(
    @SerialName(value = "name")
    val name: Name,
    @SerialName(value = "image")
    val image: String,
    @SerialName(value = "charges")
    val charges: Int
) {
    /**
     * Values: large,medium,small,other
     */
    @Serializable
    enum class Name(val value: String) {
        @SerialName(value = "large") large("large"),
        @SerialName(value = "medium") medium("medium"),
        @SerialName(value = "small") small("small"),
        @SerialName(value = "other") other("other");
    }
}
