/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.batteryapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class PromoCodeBatteryPurchaseStatusError(
    @SerialName(value = "msg")
    val msg: String,
    @SerialName(value = "code")
    val code: Code
) {
    /**
     * Values: promoMinusCodeMinusNotMinusFound,promoMinusExceededMinusAttempts,temporaryMinusError
     */
    @Serializable
    enum class Code(val value: String) {
        @SerialName(value = "promo-code-not-found") promoMinusCodeMinusNotMinusFound("promo-code-not-found"),
        @SerialName(value = "promo-exceeded-attempts") promoMinusExceededMinusAttempts("promo-exceeded-attempts"),
        @SerialName(value = "temporary-error") temporaryMinusError("temporary-error");
    }
}
