/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.batteryapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class RechargeMethodsMethodsInner(
    @SerialName(value = "type")
    val type: Type,
    @SerialName(value = "rate")
    val rate: String,
    @SerialName(value = "symbol")
    val symbol: String,
    @SerialName(value = "decimals")
    val decimals: Int,
    @SerialName(value = "support_gasless")
    val supportGasless: Boolean,
    @SerialName(value = "support_recharge")
    val supportRecharge: Boolean,
    @SerialName(value = "image")
    val image: String? = null,
    @SerialName(value = "jetton_master")
    val jettonMaster: String? = null,
    @SerialName(value = "min_bootstrap_value")
    val minBootstrapValue: String? = null
) {
    /**
     * Values: jetton,ton
     */
    @Serializable
    enum class Type(val value: String) {
        @SerialName(value = "jetton") jetton("jetton"),
        @SerialName(value = "ton") ton("ton");
    }
}
