/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.batteryapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class TransactionsTransactionsInner(
    @SerialName(value = "id")
    val id: String,

    /* represents the amount of money paid by the user for this transaction. */
    @SerialName(value = "paid_amount")
    val paidAmount: String,
    @SerialName(value = "status")
    val status: Status,
    @SerialName(value = "created_at")
    val createdAt: String
) {
    /**
     * Values: pending,completed,failed
     */
    @Serializable
    enum class Status(val value: String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "completed") completed("completed"),
        @SerialName(value = "failed") failed("failed");
    }
}
