/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tradingapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Ключ списка/полки.
 *
 * Values: top_gainers,top_losers,most_traded,core,rwa
 */
@Serializable
enum class MarketListKey(val value: String) {
    @SerialName(value = "top_gainers")
    top_gainers("top_gainers"),
    @SerialName(value = "top_losers")
    top_losers("top_losers"),
    @SerialName(value = "most_traded")
    most_traded("most_traded"),
    @SerialName(value = "core")
    core("core"),
    @SerialName(value = "rwa")
    rwa("rwa");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is MarketListKey) "$data" else null

        /**
         * Returns a valid [MarketListKey] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MarketListKey? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

