/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tradingapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class MarketListResponse(
    @Contextual @SerialName(value = "list")
    val list: MarketListKey,

    /* Элементы списка. */
    @SerialName(value = "items")
    val items: List<MarketItem>,

    /* Приблизительная свежесть данных (секунды). */
    @SerialName(value = "data_freshness_sec")
    val dataFreshnessSec: Int,

    /* Курсор следующей страницы (если включена пагинация). */
    @SerialName(value = "next_cursor")
    val nextCursor: String? = null,

    /* Предупреждения, если данные частично отсутствуют или использован fallback. */
    @SerialName(value = "warnings")
    val warnings: List<Warning>? = null
) {
}

