/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tradingapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class PerpMarket(
    @SerialName(value = "market_index")
    val marketIndex: Int,
    @SerialName(value = "symbol")
    val symbol: String,
    @SerialName(value = "base_asset")
    val baseAsset: String,
    @SerialName(value = "quote_asset")
    val quoteAsset: String,

    /* Market trading status (e.g. active, inactive). */
    @SerialName(value = "status")
    val status: String,

    /* Number of decimal places used to scale prices for signing. */
    @SerialName(value = "price_decimals")
    val priceDecimals: Int,

    /* Number of decimal places used to scale base sizes for signing. */
    @SerialName(value = "size_decimals")
    val sizeDecimals: Int,

    /* Minimum price increment, human-unit decimal string. */
    @SerialName(value = "tick_size")
    val tickSize: String,

    /* Minimum base size increment, human-unit decimal string. */
    @SerialName(value = "step_size")
    val stepSize: String,

    /* Minimum order size in base units. */
    @SerialName(value = "min_size_base")
    val minSizeBase: String,

    /* Maximum order size in base units; empty when the exchange publishes none. */
    @SerialName(value = "max_size_base")
    val maxSizeBase: String,

    /* Minimum order notional in quote units. */
    @SerialName(value = "min_size_quote")
    val minSizeQuote: String,

    /* Maximum order notional in quote units. */
    @SerialName(value = "max_size_quote")
    val maxSizeQuote: String,
    @SerialName(value = "max_leverage")
    val maxLeverage: Int,

    /* Maker fee as a percentage string. */
    @SerialName(value = "maker_fee_pct")
    val makerFeePct: String,

    /* Taker fee as a percentage string. */
    @SerialName(value = "taker_fee_pct")
    val takerFeePct: String,

    /* Initial margin fraction in basis points (1/10000). */
    @SerialName(value = "initial_margin_fraction")
    val initialMarginFraction: Int,

    /* Maintenance margin fraction in basis points (1/10000). */
    @SerialName(value = "maintenance_margin_fraction")
    val maintenanceMarginFraction: Int,

    /* Closeout margin fraction in basis points (1/10000). */
    @SerialName(value = "closeout_margin_fraction")
    val closeoutMarginFraction: Int,

    /* Open interest as reported by the exchange, decimal string. */
    @SerialName(value = "open_interest_usd")
    val openInterestUsd: String,
    @SerialName(value = "volume_24h_usd")
    val volume24hUsd: String,
    @SerialName(value = "last_price")
    val lastPrice: String,
    @SerialName(value = "index_price")
    val indexPrice: String,
    @SerialName(value = "mark_price")
    val markPrice: String,

    /* 24h price change in percent. */
    @SerialName(value = "price_change_24h")
    val priceChange24h: String,
    @SerialName(value = "high_24h")
    val high24h: String,
    @SerialName(value = "low_24h")
    val low24h: String,

    /* Current hourly funding rate, decimal string. Absent when the exchange reports none. */
    @SerialName(value = "funding_rate_hourly")
    val fundingRateHourly: String? = null,

    @Contextual @SerialName(value = "next_funding_at")
    val nextFundingAt: java.time.OffsetDateTime? = null
) {
}

