/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.tradingapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class SectionTradingActivity(
    @SerialName(value = "enabled")
    val enabled: Boolean,
    @SerialName(value = "volume_change_24h")
    val volumeChange24h: String? = null,
    @SerialName(value = "volume_24h")
    val volume24h: String? = null,
    @SerialName(value = "buy_24h")
    val buy24h: String? = null,
    @SerialName(value = "sell_24h")
    val sell24h: String? = null,
    @SerialName(value = "note")
    val note: String? = null
) {
}

