/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class CrossSwapQuote(
    /* Identifier of this quote, used for telemetry and prepare correlation */
    @SerialName(value = "quote_id")
    val quoteId: String,
    @SerialName(value = "routes")
    val routes: List<CrossSwapRoute>,

    /* Errors returned by aggregators that yielded no usable route */
    @SerialName(value = "provider_errors")
    val providerErrors: List<CrossSwapProviderError>? = null
) {
}

