/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class CrossSwapFee(
    /* Fee category emitted by the aggregator (provider-driven, free-form). */
    @SerialName(value = "type")
    val type: String,

    /* Asset the fee is denominated in (internal asset id) */
    @SerialName(value = "asset")
    val asset: String,

    /* Fee amount in minimal units */
    @SerialName(value = "amount")
    val amount: String,

    /* Chain on which the fee is paid, format `{chain}/{net}` */
    @SerialName(value = "chain_id")
    val chainId: String? = null,

    /* Fee value in USD (decimal string), if known */
    @SerialName(value = "amount_usd")
    val amountUsd: String? = null
) {
}

