/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Values: not_started,source_tx_pending,source_tx_submitted,source_tx_confirmed,bridging,streaming,destination_pending,destination_settled,refunded,failed,expired,unknown
 */
@Serializable
enum class CrossSwapExecutionStatus(val value: String) {
    @SerialName(value = "not_started")
    not_started("not_started"),
    @SerialName(value = "source_tx_pending")
    source_tx_pending("source_tx_pending"),
    @SerialName(value = "source_tx_submitted")
    source_tx_submitted("source_tx_submitted"),
    @SerialName(value = "source_tx_confirmed")
    source_tx_confirmed("source_tx_confirmed"),
    @SerialName(value = "bridging")
    bridging("bridging"),
    @SerialName(value = "streaming")
    streaming("streaming"),
    @SerialName(value = "destination_pending")
    destination_pending("destination_pending"),
    @SerialName(value = "destination_settled")
    destination_settled("destination_settled"),
    @SerialName(value = "refunded")
    refunded("refunded"),
    @SerialName(value = "failed")
    failed("failed"),
    @SerialName(value = "expired")
    expired("expired"),
    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is CrossSwapExecutionStatus) "$data" else null

        /**
         * Returns a valid [CrossSwapExecutionStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CrossSwapExecutionStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

