/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Which side of the swap the client fixes. `exact_input` (default): `source_amount` is what the user pays, routes report `estimated_destination_amount`. `exact_output`: `destination_amount` is what the user must receive, routes report the `source_amount` the user is expected to pay and `maximum_source_amount`, the cap including slippage. Only `swapsxyz` can quote `exact_output`; other aggregators are skipped and reported in `provider_errors`. 
 *
 * Values: exact_input,exact_output
 */
@Serializable
enum class CrossSwapExactType(val value: String) {
    @SerialName(value = "exact_input")
    exact_input("exact_input"),
    @SerialName(value = "exact_output")
    exact_output("exact_output");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is CrossSwapExactType) "$data" else null

        /**
         * Returns a valid [CrossSwapExactType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CrossSwapExactType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

