/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Values: no_route,asset_not_supported,min_amount_not_met,country_blocked,provider_unavailable,provider_error
 */
@Serializable
enum class CrossSwapProviderErrorCode(val value: String) {
    @SerialName(value = "no_route")
    no_route("no_route"),
    @SerialName(value = "asset_not_supported")
    asset_not_supported("asset_not_supported"),
    @SerialName(value = "min_amount_not_met")
    min_amount_not_met("min_amount_not_met"),
    @SerialName(value = "country_blocked")
    country_blocked("country_blocked"),
    @SerialName(value = "provider_unavailable")
    provider_unavailable("provider_unavailable"),
    @SerialName(value = "provider_error")
    provider_error("provider_error");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is CrossSwapProviderErrorCode) "$data" else null

        /**
         * Returns a valid [CrossSwapProviderErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CrossSwapProviderErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

