/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class CrossSwapTimeEstimate(
    /* Time to confirm the source-chain tx */
    @SerialName(value = "inbound_seconds")
    val inboundSeconds: Int? = null,

    /* Time spent inside the swap protocol */
    @SerialName(value = "swap_seconds")
    val swapSeconds: Int? = null,

    /* Time to confirm the destination-chain tx */
    @SerialName(value = "outbound_seconds")
    val outboundSeconds: Int? = null,
    @SerialName(value = "total_seconds")
    val totalSeconds: Int? = null
) {
}

