/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class CrossSwapProviderError(
    @Contextual @SerialName(value = "aggregator")
    val aggregator: CrossSwapAggregator,

    @Contextual @SerialName(value = "code")
    val code: CrossSwapProviderErrorCode,
    @SerialName(value = "message")
    val message: String,

    /* Underlying protocol or DEX that actually executes the swap (provider-driven, free-form). */
    @SerialName(value = "protocol")
    val protocol: String? = null
) {
}

