/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class CrossSwapConfig(
    /* Slippage options keyed by source-chain identifier (see `CrossSwapChain` enum, e.g. `ton`, `eth`, `btc`). Chains absent from this map fall through to a wallet-side default of 100 bps.  */
    @Contextual @SerialName(value = "slippages")
    val slippages: Map<String, CrossSwapSlippageOptions>,
    @SerialName(value = "swap_pair")
    val swapPair: CrossSwapDefaultPair
) {
}

