/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class CrossSwapHumanSummary(
    @SerialName(value = "action")
    val action: String,
    @SerialName(value = "spend_asset")
    val spendAsset: String,
    @SerialName(value = "spend_amount")
    val spendAmount: String,
    @SerialName(value = "receive_asset")
    val receiveAsset: String,
    @SerialName(value = "receive_amount")
    val receiveAmount: String? = null,

    /* Final destination of the swap (user's address on destination chain) */
    @SerialName(value = "recipient_address")
    val recipientAddress: String? = null,
    @SerialName(value = "deposit_address")
    val depositAddress: String? = null,
    @SerialName(value = "memo")
    val memo: String? = null,

    /* Underlying protocol or DEX that actually executes the swap (provider-driven, free-form). */
    @SerialName(value = "protocol")
    val protocol: String? = null,

    /* For payloads with `kind: approval`, the spender contract being authorised. Backend decodes this from the approve calldata so the wallet can verify before signing.  */
    @SerialName(value = "approval_spender")
    val approvalSpender: String? = null,

    /* For payloads with `kind: approval`, the amount being approved (in minimal units). Backend re-encodes the approve tx to enforce this value — clients can trust it matches the calldata.  */
    @SerialName(value = "approval_amount")
    val approvalAmount: String? = null,
    @SerialName(value = "warnings")
    val warnings: List<String>? = null
) {
}

