/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class ErrorResponse(
    /* Human-readable message. Sanitised — never reveals internal details. */
    @SerialName(value = "error")
    val error: String,

    /* UUID v4 for correlating the response to server logs. */
    @SerialName(value = "request_id")
    val requestId: String,

    /* Stable machine-readable error code. Optional on 5xx (server may not know the cause). Mandatory on 4xx where the client can act.  */
    @SerialName(value = "code")
    val code: String? = null
) {
}

