/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class ExchangeMerchantInfo(
    @SerialName(value = "id")
    val id: String,
    @SerialName(value = "title")
    val title: String,
    @SerialName(value = "description")
    val description: String,
    @SerialName(value = "image")
    val image: String,
    @SerialName(value = "fee")
    val fee: String,
    @SerialName(value = "buttons")
    val buttons: List<ExchangeMerchantInfoButton>
) {
}

