/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class ExchangeAvailablePair(
    @Contextual @SerialName(value = "merchant")
    val merchant: ExchangeMerchantSlug,

    @Contextual @SerialName(value = "direction")
    val direction: ExchangeDirection,
    @SerialName(value = "crypto_currency")
    val cryptoCurrency: String,
    @SerialName(value = "crypto_network")
    val cryptoNetwork: String,
    @SerialName(value = "fiat_currency")
    val fiatCurrency: String,
    @SerialName(value = "limits")
    val limits: ExchangeLimits? = null,
    @SerialName(value = "payment_methods")
    val paymentMethods: List<@Contextual ExchangePaymentMethodType>? = null
) {
}

