/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class OfframpQuoteRequest(
    @SerialName(value = "source_asset_id")
    val sourceAssetId: String,
    @SerialName(value = "fiat")
    val fiat: String,

    /* Source crypto decimal. When `reverse=true`, target fiat */
    @SerialName(value = "amount")
    val amount: String,
    @SerialName(value = "reverse")
    val reverse: Boolean? = null,

    @Contextual @SerialName(value = "payout_method")
    val payoutMethod: ExchangePaymentMethodType? = null,

    @Contextual @SerialName(value = "merchant")
    val merchant: ExchangeMerchantSlug? = null
) {
}

