/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Happy path: `created → awaiting_payment → payment_received → funds_sent → completed`. Terminal: `completed`, `failed`, `cancelled`, `expired`, `refunded`. 
 *
 * Values: created,awaiting_payment,payment_received,funds_sent,completed,failed,cancelled,expired,refunded
 */
@Serializable
enum class OnrampOrderStatus(val value: String) {
    @SerialName(value = "created")
    created("created"),
    @SerialName(value = "awaiting_payment")
    awaiting_payment("awaiting_payment"),
    @SerialName(value = "payment_received")
    payment_received("payment_received"),
    @SerialName(value = "funds_sent")
    funds_sent("funds_sent"),
    @SerialName(value = "completed")
    completed("completed"),
    @SerialName(value = "failed")
    failed("failed"),
    @SerialName(value = "cancelled")
    cancelled("cancelled"),
    @SerialName(value = "expired")
    expired("expired"),
    @SerialName(value = "refunded")
    refunded("refunded");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is OnrampOrderStatus) "$data" else null

        /**
         * Returns a valid [OnrampOrderStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OnrampOrderStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

