/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.exchangeapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class SwapGas(
    @SerialName(value = "dedust")
    val dedust: SwapGasDedust,
    @SerialName(value = "stonfi")
    val stonfi: SwapGasDedust,
    @SerialName(value = "omniston")
    val omniston: SwapGasDedust
) {
}

