/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.perpsapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Account(
    @SerialName(value = "account_index")
    val accountIndex: Int? = null,

    /* L1 (Ethereum) address keying this main account. */
    @SerialName(value = "l1_address")
    val l1Address: String? = null,

    @Contextual @SerialName(value = "status")
    val status: AccountStatus? = null,

    /* Whether an L2 signing key is registered (ChangePubKey done). Independent of status: it comes from the account's API keys, not from the account record. */
    @SerialName(value = "has_l2_key")
    val hasL2Key: Boolean? = null,

    /* Total collateral, human-unit decimal string. */
    @SerialName(value = "collateral")
    val collateral: String? = null,

    /* Balance available for new orders, human-unit decimal string. */
    @SerialName(value = "available_balance")
    val availableBalance: String? = null,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime? = null
) {
}

