/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.perpsapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Balance(
    @SerialName(value = "currency")
    val currency: String? = null,
    @SerialName(value = "equity")
    val equity: String? = null,
    @SerialName(value = "available_balance")
    val availableBalance: String? = null,
    @SerialName(value = "transferable_balance")
    val transferableBalance: String? = null,
    @SerialName(value = "unrealized_pnl_total")
    val unrealizedPnlTotal: String? = null,
    @SerialName(value = "collateral")
    val collateral: String? = null
) {
}

