/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.perpsapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Deposit(
    /* Identifies this deposit when polling its progress. A random UUID, so it cannot be guessed from an address or a sequence, but it is not what authorises the poll -- that is the wallet the deposit belongs to, see the GET operation. Worth persisting alongside whatever the client calls the attempt, and not fatal to lose, since posting the same transaction again returns the same id rather than a second deposit. */
    @SerialName(value = "deposit_id")
    val depositId: String? = null,

    /* pending until Lighter credits the funds (credited) or nothing has arrived within the waiting window (unfunded). unfunded means the deposit was not confirmed while it was being watched, which is not quite the same as the money never arriving: what arrives is Lighter's to say and this record only tracks it. A deposit credited after the window is not noticed, so an unfunded record is where such a deposit stays. Treat it as \"we did not see it\", not as proof of loss, and check the account balance before telling anyone their money is gone. */
    @SerialName(value = "status")
    val status: Status? = null,

    /* The network and token the funds were sent as; echoed from the request. */
    @SerialName(value = "asset_id")
    val assetId: String? = null,

    /* What the caller declared, echoed back. Compare with credited_amount. */
    @SerialName(value = "amount")
    val amount: String? = null,

    /* What Lighter actually credited, once it has. Absent while the deposit is pending, and also on the rare credit confirmed without an amount — where the only signal was an account appearing, which proves an arrival but not its size. */
    @SerialName(value = "credited_amount")
    val creditedAmount: String? = null,

    /* The Ethereum transaction this deposit was recorded against, echoed back. */
    @SerialName(value = "l1_tx_hash")
    val l1TxHash: String? = null,

    /* The Lighter account the deposit belongs to. Absent until the account exists, which for a first deposit is until it is credited — that deposit is what creates it. */
    @SerialName(value = "account_index")
    val accountIndex: Long? = null,

    /* When the deposit was recorded here. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    /* When it stopped being pending. Absent while it still is. */
    @Contextual @SerialName(value = "closed_at")
    val closedAt: java.time.OffsetDateTime? = null
) {
    /**
     * pending until Lighter credits the funds (credited) or nothing has arrived within the waiting window (unfunded). unfunded means the deposit was not confirmed while it was being watched, which is not quite the same as the money never arriving: what arrives is Lighter's to say and this record only tracks it. A deposit credited after the window is not noticed, so an unfunded record is where such a deposit stays. Treat it as \"we did not see it\", not as proof of loss, and check the account balance before telling anyone their money is gone.
     *
     * Values: pending,credited,unfunded
     */
    @Serializable
    enum class Status(val value: String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "credited") credited("credited"),
        @SerialName(value = "unfunded") unfunded("unfunded");
    }
}
