/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.perpsapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class OpenPositionDetail(
    @SerialName(value = "position")
    val position: OpenPosition? = null,

    /* Whether the legs were read. False means they were not: the wallet has stored no read-only token, the stored one expired, or it could not be decrypted. A client must not read a null auto_close as \"none\" while this is false -- offering to set a take-profit over an existing one would replace it. */
    @SerialName(value = "auto_close_known")
    val autoCloseKnown: Boolean? = null,

    /* The legs, or null when there are none -- or when auto_close_known is false. */
    @SerialName(value = "auto_close")
    val autoClose: PositionAutoClose? = null
) {
}

