/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.perpsapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class OpenDepositRequest(
    /* Opaque client-side identifier for this deposit attempt, never parsed here. Retrying the same attempt must reuse it — that is what makes this call idempotent — and a genuinely new deposit must carry a new one. Reusing it with a different amount is a conflict, not an update. A write key only. Progress is read by deposit_id, and this value is not a lookup key: recording the same transaction under a second operation_id returns the record created under the first one, keeping the first one's value. */
    @SerialName(value = "operation_id")
    val operationId: String,

    /* Where the funds started, in the swap backend's own asset id form. Opaque here: kept as a record and never resolved, because what arrives at Lighter is USDC on Ethereum whichever chain the money came from. */
    @SerialName(value = "asset_id")
    val assetId: String,

    /* What was sent, as a decimal string, at most 6 decimal places and not below the gateway's 1 USDC floor — less than that is accepted by the contract and then never credited. Kept as declared: Lighter records only what arrives, so this is the only copy of what was meant, and \"expected N, got M\" can be answered from nowhere else. */
    @SerialName(value = "amount")
    val amount: String,

    /* The Ethereum transaction that called Lighter's gateway. Required: it is the only handle this service can confirm a deposit with — Lighter resolves it to the credit, the amount and the account index, and does so without a read-only token, which a first deposit could not have anyway since the account does not exist yet. Only the Ethereum hash counts. A caller that paid from another chain holds a source-chain hash, which Lighter has never seen; it has to wait for the aggregator to deliver and record the deposit then. That restriction is temporary and will be lifted once execution_id can be resolved to the delivered hash server-side. */
    @SerialName(value = "l1_tx_hash")
    val l1TxHash: String,

    /* The wallet's consent to this deposit, signed with its own root key: hex of a 65-byte recoverable secp256k1 signature (R | S | V) over LP(\"perps.deposit.register.v1\") | LP(wallet_id) | LP(l1_address) | LP(operation_id) | LP(amount) | LP(asset_id) | LP(l1_tx_hash) | LP(execution_id), in the same length-prefixed framing custodial-battery uses for its send proof. Every term as this service records it: as sent here with surrounding whitespace trimmed and l1_tx_hash lowercased, execution_id an empty string when omitted, l1_address lowercase with its 0x. Note that l1_address is named here and nowhere in the body. signature only proves that somebody holds the key to an address; this is the wallet saying which address is its own. Both are needed on a first deposit: without this one an EIP-712 signature captured anywhere could bind this wallet to a stranger's Lighter account. Required on every deposit, and absent answers 401 operation_proof_required. Requires a format 2 wallet_id, which every multichain wallet has. */
    @SerialName(value = "proof")
    val proof: String,

    /* The swap this deposit is funded by, as the swap backend named it. Optional, kept for correlation and support: it is what a failed swap is told apart by, and what a server-side resolver will one day turn into the Ethereum hash so that l1_tx_hash stops being required. Nothing reads it yet. */
    @SerialName(value = "execution_id")
    val executionId: String? = null,

    /* Unix seconds past which the signature below is refused, capped by the service at ten minutes ahead. Travels with signature: one without the other is a 400, because a missing deadline would otherwise be reported as a signature that has expired. */
    @SerialName(value = "deadline")
    val deadline: Long? = null,

    /* EIP-712 signature proving the caller holds the key to the L1 address this deposit is recorded against, over LinkWallet(string walletId,uint64 deadline) under domain {name: TonkeeperPerps, version: \"1\", chainId: 1} with no verifyingContract. Encoded as 65 bytes of r‖s‖v hex; v may be 27/28 or 0/1, and the high-s form is refused. Send it every time, signed in the same vault unlock as the deposit transaction: it is read only while the wallet has proved no address yet, and the client cannot tell when that is. Missing when it is needed answers 400 address_proof_required. */
    @SerialName(value = "signature")
    val signature: String? = null
) {
}

