/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.perpsapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Collapsed public order status (Lighter internal sub-statuses are never leaked).
 *
 * Values: new,`open`,filled,partially_filled,canceled,rejected
 */
@Serializable
enum class OrderStatus(val value: String) {
    @SerialName(value = "new")
    new("new"),
    @SerialName(value = "open")
    `open`("open"),
    @SerialName(value = "filled")
    filled("filled"),
    @SerialName(value = "partially_filled")
    partially_filled("partially_filled"),
    @SerialName(value = "canceled")
    canceled("canceled"),
    @SerialName(value = "rejected")
    rejected("rejected");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is OrderStatus) "$data" else null

        /**
         * Returns a valid [OrderStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OrderStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

