/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.perpsapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class ReportedTransaction(
    @Contextual @SerialName(value = "type")
    val type: TransactionType,

    /* Lighter transaction hash, computed client-side from the signed transaction and therefore known before the venue replies. It becomes the event_id consumers deduplicate on, so the same submission must always be reported under the same hash. */
    @SerialName(value = "tx_hash")
    val txHash: String
) {
}

