/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Activity(
    @Contextual @SerialName(value = "activity_type")
    val activityType: ActivityType,

    @Contextual @SerialName(value = "status")
    val status: ActivityStatus,

    @Contextual @SerialName(value = "block_time")
    val blockTime: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "from_chain")
    val fromChain: Chain,

    @Contextual @SerialName(value = "to_chain")
    val toChain: Chain,

    @Contextual @SerialName(value = "direction")
    val direction: ActivityDirection,

    /* On-chain tx identifiers, format: chain:txhash */
    @SerialName(value = "tx_ids")
    val txIds: List<String>,
    @SerialName(value = "block_number")
    val blockNumber: Long? = null,
    @SerialName(value = "wallet_address")
    val walletAddress: String? = null,
    @SerialName(value = "from_address")
    val fromAddress: String? = null,
    @SerialName(value = "to_address")
    val toAddress: String? = null,
    @SerialName(value = "out_token")
    val outToken: AssetInfo? = null,
    @SerialName(value = "out_amount")
    val outAmount: String? = null,
    @SerialName(value = "out_amount_usd")
    @Deprecated(message = "This property is deprecated.")
    val outAmountUsd: Double? = null,

    /* Current price per currency, e.g. {\"USD\": \"0.999\", \"TON\": \"0.789\"} */
    @SerialName(value = "out_fiat_price")
    val outFiatPrice: Map<String, String>? = null,
    @SerialName(value = "in_token")
    val inToken: AssetInfo? = null,
    @SerialName(value = "in_amount")
    val inAmount: String? = null,
    @SerialName(value = "in_amount_usd")
    @Deprecated(message = "This property is deprecated.")
    val inAmountUsd: Double? = null,

    /* Current price per currency, e.g. {\"USD\": \"0.999\", \"TON\": \"0.789\"} */
    @SerialName(value = "in_fiat_price")
    val inFiatPrice: Map<String, String>? = null,

    @Contextual @SerialName(value = "fee_type")
    val feeType: ActivityFeeType? = null,
    @SerialName(value = "fee_token")
    val feeToken: AssetInfo? = null,
    @SerialName(value = "fee_amount")
    val feeAmount: String? = null,
    @SerialName(value = "fee_amount_usd")
    @Deprecated(message = "This property is deprecated.")
    val feeAmountUsd: Double? = null,

    /* Current price per currency, e.g. {\"USD\": \"0.999\", \"TON\": \"0.789\"} */
    @SerialName(value = "fee_fiat_price")
    val feeFiatPrice: Map<String, String>? = null,
    @SerialName(value = "fee")
    val fee: ActivityFee? = null,

    /* DEX/bridge protocol name (uniswap_v3, stargate, etc.) */
    @SerialName(value = "protocol")
    val protocol: String? = null,

    /* Ready-to-open explorer URL for the primary tx (source chain for cross-chain bridges). Omitted when the chain has no known explorer template — clients should hide the link in that case. */
    @SerialName(value = "explorer_url")
    val explorerUrl: String? = null,

    /* Has the wallet owner acknowledged this activity in the app. Client-driven flag. */
    @SerialName(value = "is_read")
    val isRead: Boolean? = null,

    /* Backend-classified spam flag on this specific activity. Clients may hide by default or show a warning badge. */
    @SerialName(value = "is_spam")
    val isSpam: Boolean? = null,

    /* Chain-specific extras (memo, input data, etc.). Known fields: `comment` — plaintext memo attached to the transfer; `encrypted_comment` — `{encryption_type, cipher_text}` of a memo only the recipient can read; `tron_resource` — `{energy, bandwidth}`, what a TRON transaction cost its sender in resources. Energy and bandwidth are resource units, the two fees are sun of the TRX fee spent on each. A sender with staked energy or free bandwidth burns no TRX at all, so `fee_amount` of 0 is the normal case there and this object is the real cost. */
    @Contextual @SerialName(value = "meta")
    val meta: Map<String, io.JsonAny>? = null
) {
}

