/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Asset(
    @SerialName(value = "asset")
    val asset: AssetInfo,

    /* Account address this balance belongs to. Lets clients distinguish multiple accounts on the same chain (e.g. TON v4R2 + v5R1). */
    @SerialName(value = "address")
    val address: String,
    @SerialName(value = "price")
    val price: AssetPrice,

    /* True when the user has hidden this asset from their balances; the row is still returned so the client can offer it back. */
    @SerialName(value = "is_hidden")
    val isHidden: Boolean,

    /* Balance in minimal units (wei, nanoton, satoshi, sun) */
    @SerialName(value = "balance")
    val balance: String,

    /* Account sub-type, mirrors WalletAccount.type (TON v4R2/v5R1, BTC p2wpkh/p2tr). Omitted for EVM/TRON. */
    @SerialName(value = "type")
    val type: String? = null,

    /* asset_id of the spot asset this one is linked to, e.g. the market a Lighter perp tracks. Omitted when there is no link. */
    @SerialName(value = "reference_id")
    val referenceId: String? = null
) {
}

