/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Capability flag. Clients must tolerate unknown values added later
 *
 * Values: onramp,offramp,swap,p2p
 */
@Serializable
enum class AssetCapability(val value: String) {
    @SerialName(value = "onramp")
    onramp("onramp"),
    @SerialName(value = "offramp")
    offramp("offramp"),
    @SerialName(value = "swap")
    swap("swap"),
    @SerialName(value = "p2p")
    p2p("p2p");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): String? = if (data is AssetCapability) "$data" else null

        /**
         * Returns a valid [AssetCapability] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AssetCapability? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

