/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class RaffleCTA(
    @SerialName(value = "title")
    val title: String,
    @SerialName(value = "action")
    val action: Action,
    @SerialName(value = "payload")
    val payload: String
) {
    /**
     * Values: deeplink,link
     */
    @Serializable
    enum class Action(val value: String) {
        @SerialName(value = "deeplink") deeplink("deeplink"),
        @SerialName(value = "link") link("link");
    }
}
