/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class SaveWalletAssetsFiltersRequest(
    /* One entry per asset the user toggled. Capped so a single call cannot rewrite a whole catalogue. */
    @SerialName(value = "changes")
    val changes: List<SaveWalletAssetsFiltersRequestChangesInner>
) {
}

