/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class SummaryAsset(
    @SerialName(value = "asset")
    val asset: AssetInfo,
    @SerialName(value = "price")
    val price: AssetPrice,

    /* Current price per currency, e.g. {\"USD\": \"0.999\", \"TON\": \"0.789\"} */
    @SerialName(value = "market_cap")
    val marketCap: Map<String, String>,

    /* asset_id of the spot asset this one is linked to, e.g. the market a Lighter perp tracks. Omitted when there is no link. */
    @SerialName(value = "reference_id")
    val referenceId: String? = null
) {
}

