/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class Wallet(
    /* Stable wallet identifier */
    @SerialName(value = "wallet_id")
    val walletId: String,
    @SerialName(value = "accounts")
    val accounts: List<WalletAccount>,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,
    @SerialName(value = "sync_status")
    val syncStatus: SyncStatus
) {
}

