/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class WalletRegisterItem(
    /* `accounts_digest` = blake2b-256 over the compact JSON array of `{address, chain, network, type?}` objects, sorted by (address, chain, network, type). */
    @SerialName(value = "accounts")
    val accounts: List<WalletAccount>,

    /* Format 2 wallet_id: `base32(format ‖ kind_byte ‖ blake2b160(LP(\"keeper.wallet.id.v2\") ‖ LP(kind) ‖ LP(rootPub)))`, where `format` = 2 and `kind_byte` = 1 for multichain. */
    @SerialName(value = "wallet_id")
    val walletId: String? = null,

    /* Signature by the wallet root key: 65 bytes (130 hex) secp256k1 recoverable, laid out `R ‖ S ‖ V` as on EVM. Message layout is in BACKEND.md. */
    @SerialName(value = "wallet_proof")
    val walletProof: String? = null
) {
}

