/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

@Serializable
data class WalletRegisterResult(
    /* Position of this item in the request array */
    @SerialName(value = "index")
    val index: Int,
    @SerialName(value = "status")
    val status: Status,

    /* The id the wallet is filed under, present when status=ok. */
    @SerialName(value = "wallet_id")
    val walletId: String? = null,

    /* Machine-readable reason when status=failed: invalid_proof, invalid_accounts, invalid_wallet_id, missing_wallet_id, missing_wallet_proof, invalid_wallet_proof, storage_error, wallet_limit_reached, device_limit_reached. */
    @SerialName(value = "error")
    val error: String? = null
) {
    /**
     * Values: ok,failed
     */
    @Serializable
    enum class Status(val value: String) {
        @SerialName(value = "ok") ok("ok"),
        @SerialName(value = "failed") failed("failed");
    }
}
