/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 * @param productId 
 * @param promo 
 */


data class AndroidBatteryPurchaseRequestPurchasesInner (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "product_id")
    val productId: kotlin.String,

    @Json(name = "promo")
    val promo: kotlin.String? = null

) {


}

