/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.CreatePromoCampaign200ResponseParticipantsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param participants 
 */


data class CreatePromoCampaign200Response (

    @Json(name = "participants")
    val participants: kotlin.collections.List<CreatePromoCampaign200ResponseParticipantsInner>

) {


}

