/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param boc 
 */


data class EmulateMessageToWalletRequest (

    @Json(name = "boc")
    val boc: kotlin.String,

    @Json(name = "message")
    val version: kotlin.String? = null,

    @Json(name = "platform")
    val platform: kotlin.String? = null,

    @Json(name = "source")
    val source: kotlin.String? = null,

    @Json(name = "confirmation_time")
    val confirmationTime: kotlin.Double? = null

) {


}

