/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param wallet 
 * @param tx 
 * @param energy 
 * @param bandwidth 
 */


data class TronSendRequest (

    @Json(name = "wallet")
    val wallet: kotlin.String,

    @Json(name = "tx")
    val tx: kotlin.String? = null,

    @Json(name = "energy")
    val energy: kotlin.Int? = null,

    @Json(name = "bandwidth")
    val bandwidth: kotlin.Int? = null

) {


}

