/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.walletapi.models.AuthChallenge
import io.walletapi.models.DeviceTokens
import io.walletapi.models.GetDeviceBindings200Response
import io.walletapi.models.GetDeviceBindingsRequest
import io.walletapi.models.Healthcheck500Response
import io.walletapi.models.Jwks
import io.walletapi.models.Ok
import io.walletapi.models.RefreshDeviceRequest
import io.walletapi.models.RegisterDeviceRequest
import io.walletapi.models.RegisterWallets200Response
import io.walletapi.models.RegisterWalletsRequest
import io.walletapi.models.SubscribeDevicePushRequest
import io.walletapi.models.UnregisterWallets200Response
import io.walletapi.models.UnregisterWalletsRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import io.infrastructure.ApiClient
import io.infrastructure.ApiResponse
import io.infrastructure.ClientException
import io.infrastructure.ClientError
import io.infrastructure.ServerException
import io.infrastructure.ServerError
import io.infrastructure.MultiValueMap
import io.infrastructure.PartConfig
import io.infrastructure.RequestConfig
import io.infrastructure.RequestMethod
import io.infrastructure.ResponseType
import io.infrastructure.Success
import io.infrastructure.toMultiValue

class AuthApi(basePath: String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getDeviceBindings(getDeviceBindingsRequest: GetDeviceBindingsRequest, F: String? = null): GetDeviceBindings200Response {
        val localVarResponse = getDeviceBindingsWithHttpInfo(getDeviceBindingsRequest = getDeviceBindingsRequest, F = F)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetDeviceBindings200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getDeviceBindingsWithHttpInfo(getDeviceBindingsRequest: GetDeviceBindingsRequest, F: String?): ApiResponse<GetDeviceBindings200Response?> {
        val localVariableConfig = getDeviceBindingsRequestConfig(getDeviceBindingsRequest = getDeviceBindingsRequest, F = F)

        return request<GetDeviceBindingsRequest, GetDeviceBindings200Response>(
            localVariableConfig
        )
    }

    fun getDeviceBindingsRequestConfig(getDeviceBindingsRequest: GetDeviceBindingsRequest, F: String?): RequestConfig<GetDeviceBindingsRequest> {
        val localVariableBody = getDeviceBindingsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        F?.apply { localVariableHeaders["F"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/devices/bindings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getDeviceChallenge(): AuthChallenge {
        val localVarResponse = getDeviceChallengeWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AuthChallenge
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getDeviceChallengeWithHttpInfo(): ApiResponse<AuthChallenge?> {
        val localVariableConfig = getDeviceChallengeRequestConfig()

        return request<Unit, AuthChallenge>(
            localVariableConfig
        )
    }

    fun getDeviceChallengeRequestConfig(): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v2/devices/challenge",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getJwks(): Jwks {
        val localVarResponse = getJwksWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Jwks
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getJwksWithHttpInfo(): ApiResponse<Jwks?> {
        val localVariableConfig = getJwksRequestConfig()

        return request<Unit, Jwks>(
            localVariableConfig
        )
    }

    fun getJwksRequestConfig(): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/auth/.well-known/jwks.json",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun logoutDevice(): Ok {
        val localVarResponse = logoutDeviceWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Ok
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun logoutDeviceWithHttpInfo(): ApiResponse<Ok?> {
        val localVariableConfig = logoutDeviceRequestConfig()

        return request<Unit, Ok>(
            localVariableConfig
        )
    }

    fun logoutDeviceRequestConfig(): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/devices/logout",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refreshDevice(refreshDeviceRequest: RefreshDeviceRequest): DeviceTokens {
        val localVarResponse = refreshDeviceWithHttpInfo(refreshDeviceRequest = refreshDeviceRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeviceTokens
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun refreshDeviceWithHttpInfo(refreshDeviceRequest: RefreshDeviceRequest): ApiResponse<DeviceTokens?> {
        val localVariableConfig = refreshDeviceRequestConfig(refreshDeviceRequest = refreshDeviceRequest)

        return request<RefreshDeviceRequest, DeviceTokens>(
            localVariableConfig
        )
    }

    fun refreshDeviceRequestConfig(refreshDeviceRequest: RefreshDeviceRequest): RequestConfig<RefreshDeviceRequest> {
        val localVariableBody = refreshDeviceRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/devices/refresh",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun registerDevice(registerDeviceRequest: RegisterDeviceRequest): DeviceTokens {
        val localVarResponse = registerDeviceWithHttpInfo(registerDeviceRequest = registerDeviceRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeviceTokens
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun registerDeviceWithHttpInfo(registerDeviceRequest: RegisterDeviceRequest): ApiResponse<DeviceTokens?> {
        val localVariableConfig = registerDeviceRequestConfig(registerDeviceRequest = registerDeviceRequest)

        return request<RegisterDeviceRequest, DeviceTokens>(
            localVariableConfig
        )
    }

    fun registerDeviceRequestConfig(registerDeviceRequest: RegisterDeviceRequest): RequestConfig<RegisterDeviceRequest> {
        val localVariableBody = registerDeviceRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/devices/register",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun registerWallets(registerWalletsRequest: RegisterWalletsRequest, F: String? = null): RegisterWallets200Response {
        val localVarResponse = registerWalletsWithHttpInfo(registerWalletsRequest = registerWalletsRequest, F = F)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RegisterWallets200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun registerWalletsWithHttpInfo(registerWalletsRequest: RegisterWalletsRequest, F: String?): ApiResponse<RegisterWallets200Response?> {
        val localVariableConfig = registerWalletsRequestConfig(registerWalletsRequest = registerWalletsRequest, F = F)

        return request<RegisterWalletsRequest, RegisterWallets200Response>(
            localVariableConfig
        )
    }

    fun registerWalletsRequestConfig(registerWalletsRequest: RegisterWalletsRequest, F: String?): RequestConfig<RegisterWalletsRequest> {
        val localVariableBody = registerWalletsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        F?.apply { localVariableHeaders["F"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/wallets/register",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscribeDevicePush(subscribeDevicePushRequest: SubscribeDevicePushRequest, F: String? = null): Ok {
        val localVarResponse = subscribeDevicePushWithHttpInfo(subscribeDevicePushRequest = subscribeDevicePushRequest, F = F)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Ok
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun subscribeDevicePushWithHttpInfo(subscribeDevicePushRequest: SubscribeDevicePushRequest, F: String?): ApiResponse<Ok?> {
        val localVariableConfig = subscribeDevicePushRequestConfig(subscribeDevicePushRequest = subscribeDevicePushRequest, F = F)

        return request<SubscribeDevicePushRequest, Ok>(
            localVariableConfig
        )
    }

    fun subscribeDevicePushRequestConfig(subscribeDevicePushRequest: SubscribeDevicePushRequest, F: String?): RequestConfig<SubscribeDevicePushRequest> {
        val localVariableBody = subscribeDevicePushRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        F?.apply { localVariableHeaders["F"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/wallets/push/subscribe",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unregisterWallets(unregisterWalletsRequest: UnregisterWalletsRequest): UnregisterWallets200Response {
        val localVarResponse = unregisterWalletsWithHttpInfo(unregisterWalletsRequest = unregisterWalletsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as UnregisterWallets200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun unregisterWalletsWithHttpInfo(unregisterWalletsRequest: UnregisterWalletsRequest): ApiResponse<UnregisterWallets200Response?> {
        val localVariableConfig = unregisterWalletsRequestConfig(unregisterWalletsRequest = unregisterWalletsRequest)

        return request<UnregisterWalletsRequest, UnregisterWallets200Response>(
            localVariableConfig
        )
    }

    fun unregisterWalletsRequestConfig(unregisterWalletsRequest: UnregisterWalletsRequest): RequestConfig<UnregisterWalletsRequest> {
        val localVariableBody = unregisterWalletsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/wallets/unregister",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unsubscribeDevicePush(): Ok {
        val localVarResponse = unsubscribeDevicePushWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Ok
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun unsubscribeDevicePushWithHttpInfo(): ApiResponse<Ok?> {
        val localVariableConfig = unsubscribeDevicePushRequestConfig()

        return request<Unit, Ok>(
            localVariableConfig
        )
    }

    fun unsubscribeDevicePushRequestConfig(): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/wallets/push/unsubscribe",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    private fun encodeURIComponent(uriComponent: String): String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
