/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by the Tonapi OpenAPI Generator.
 * Generator: OpenAPI Generator (https://openapi-generator.tech)
 *
 * To regenerate, run: ./tools/scripts/generators/tonapi/update-all.sh
 * Manual changes will be overwritten on next generation.
 */

package io.walletapi.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.walletapi.models.ForcePickRaffleWinners200Response
import io.walletapi.models.ForcePickRaffleWinnersRequest
import io.walletapi.models.GetWalletRaffles200Response
import io.walletapi.models.Healthcheck500Response
import io.walletapi.models.MarkWalletRaffleImportRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import io.infrastructure.ApiClient
import io.infrastructure.ApiResponse
import io.infrastructure.ClientException
import io.infrastructure.ClientError
import io.infrastructure.ServerException
import io.infrastructure.ServerError
import io.infrastructure.MultiValueMap
import io.infrastructure.PartConfig
import io.infrastructure.RequestConfig
import io.infrastructure.RequestMethod
import io.infrastructure.ResponseType
import io.infrastructure.Success
import io.infrastructure.toMultiValue

class RafflesApi(basePath: String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun completeWalletRaffleMigration(walletId: String, xWalletId: String? = walletId): Unit {
        val localVarResponse = completeWalletRaffleMigrationWithHttpInfo(walletId = walletId, xWalletId = xWalletId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Throws(IllegalStateException::class, IOException::class)
    fun completeWalletRaffleMigrationWithHttpInfo(walletId: String, xWalletId: String?): ApiResponse<Unit?> {
        val localVariableConfig = completeWalletRaffleMigrationRequestConfig(walletId = walletId, xWalletId = xWalletId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    fun completeWalletRaffleMigrationRequestConfig(walletId: String, xWalletId: String?): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xWalletId?.apply { localVariableHeaders["X-Wallet-ID"] = this }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/wallets/{wallet_id}/raffles/migration".replace("{"+"wallet_id"+"}", encodeURIComponent(walletId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            requiresWalletAuthentication = true,
            walletId = xWalletId,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun forcePickRaffleWinners(raffleId: String, forcePickRaffleWinnersRequest: ForcePickRaffleWinnersRequest? = null): ForcePickRaffleWinners200Response {
        val localVarResponse = forcePickRaffleWinnersWithHttpInfo(raffleId = raffleId, forcePickRaffleWinnersRequest = forcePickRaffleWinnersRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ForcePickRaffleWinners200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun forcePickRaffleWinnersWithHttpInfo(raffleId: String, forcePickRaffleWinnersRequest: ForcePickRaffleWinnersRequest?): ApiResponse<ForcePickRaffleWinners200Response?> {
        val localVariableConfig = forcePickRaffleWinnersRequestConfig(raffleId = raffleId, forcePickRaffleWinnersRequest = forcePickRaffleWinnersRequest)

        return request<ForcePickRaffleWinnersRequest, ForcePickRaffleWinners200Response>(
            localVariableConfig
        )
    }

    fun forcePickRaffleWinnersRequestConfig(raffleId: String, forcePickRaffleWinnersRequest: ForcePickRaffleWinnersRequest?): RequestConfig<ForcePickRaffleWinnersRequest> {
        val localVariableBody = forcePickRaffleWinnersRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/raffles/{raffle_id}/pick-winners".replace("{"+"raffle_id"+"}", encodeURIComponent(raffleId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getWalletRaffles(walletId: String, lang: String? = "en", ids: List<String>? = null, debugNow: java.time.OffsetDateTime? = null, isNew: Boolean? = false, xWalletId: String? = walletId): GetWalletRaffles200Response {
        val localVarResponse = getWalletRafflesWithHttpInfo(walletId = walletId, lang = lang, ids = ids, debugNow = debugNow, isNew = isNew, xWalletId = xWalletId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetWalletRaffles200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getWalletRafflesWithHttpInfo(walletId: String, lang: String?, ids: List<String>?, debugNow: java.time.OffsetDateTime?, isNew: Boolean?, xWalletId: String?): ApiResponse<GetWalletRaffles200Response?> {
        val localVariableConfig = getWalletRafflesRequestConfig(walletId = walletId, lang = lang, ids = ids, debugNow = debugNow, isNew = isNew, xWalletId = xWalletId)

        return request<Unit, GetWalletRaffles200Response>(
            localVariableConfig
        )
    }

    fun getWalletRafflesRequestConfig(walletId: String, lang: String?, ids: List<String>?, debugNow: java.time.OffsetDateTime?, isNew: Boolean?, xWalletId: String?): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<String, List<String>>()
            .apply {
                if (lang != null) {
                    put("lang", listOf(lang.toString()))
                }
                if (ids != null) {
                    put("ids", toMultiValue(ids.toList(), "csv"))
                }
                if (debugNow != null) {
                    put("_debug_now", listOf(parseDateToQueryString(debugNow)))
                }
                if (isNew != null) {
                    put("is_new", listOf(isNew.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xWalletId?.apply { localVariableHeaders["X-Wallet-ID"] = this }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/wallets/{wallet_id}/raffles".replace("{"+"wallet_id"+"}", encodeURIComponent(walletId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            requiresWalletAuthentication = true,
            walletId = xWalletId,
            body = localVariableBody
        )
    }

    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun markWalletRaffleImport(walletId: String, markWalletRaffleImportRequest: MarkWalletRaffleImportRequest, xWalletId: String? = walletId): Unit {
        val localVarResponse = markWalletRaffleImportWithHttpInfo(walletId = walletId, markWalletRaffleImportRequest = markWalletRaffleImportRequest, xWalletId = xWalletId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    @Throws(IllegalStateException::class, IOException::class)
    fun markWalletRaffleImportWithHttpInfo(walletId: String, markWalletRaffleImportRequest: MarkWalletRaffleImportRequest, xWalletId: String?): ApiResponse<Unit?> {
        val localVariableConfig = markWalletRaffleImportRequestConfig(walletId = walletId, markWalletRaffleImportRequest = markWalletRaffleImportRequest, xWalletId = xWalletId)

        return request<MarkWalletRaffleImportRequest, Unit>(
            localVariableConfig
        )
    }

    fun markWalletRaffleImportRequestConfig(walletId: String, markWalletRaffleImportRequest: MarkWalletRaffleImportRequest, xWalletId: String?): RequestConfig<MarkWalletRaffleImportRequest> {
        val localVariableBody = markWalletRaffleImportRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xWalletId?.apply { localVariableHeaders["X-Wallet-ID"] = this }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/wallets/{wallet_id}/raffles/import".replace("{"+"wallet_id"+"}", encodeURIComponent(walletId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            requiresWalletAuthentication = true,
            walletId = xWalletId,
            body = localVariableBody
        )
    }

    private fun encodeURIComponent(uriComponent: String): String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
