package uikit.compose

import androidx.annotation.ColorRes
import com.tonapps.uikit.color.R

sealed class AppTheme(
    @ColorRes val textPrimaryColorRes: Int,
    @ColorRes val textSecondaryColorRes: Int,
    @ColorRes val textTertiaryColorRes: Int,
    @ColorRes val textAccentColorRes: Int,
    @ColorRes val textPrimaryAlternateColorRes: Int,

    @ColorRes val backgroundPageColorRes: Int,
    @ColorRes val backgroundTransparentColorRes: Int,
    @ColorRes val backgroundContentColorRes: Int,
    @ColorRes val backgroundContentTintColorRes: Int,
    @ColorRes val backgroundContentAttentionColorRes: Int,
    @ColorRes val backgroundHighlightedColorRes: Int,
    @ColorRes val backgroundOverlayStrongColorRes: Int,
    @ColorRes val backgroundOverlayLightColorRes: Int,
    @ColorRes val backgroundOverlayExtraLightColorRes: Int,

    @ColorRes val iconPrimaryColorRes: Int,
    @ColorRes val iconSecondaryColorRes: Int,
    @ColorRes val iconTertiaryColorRes: Int,
    @ColorRes val iconPrimaryAlternateColorRes: Int,

    @ColorRes val buttonPrimaryBackgroundColorRes: Int,
    @ColorRes val buttonPrimaryBackgroundDisabledColorRes: Int,
    @ColorRes val buttonPrimaryBackgroundHighlightedColorRes: Int,
    @ColorRes val buttonPrimaryForegroundColorRes: Int,

    @ColorRes val buttonSecondaryBackgroundColorRes: Int,
    @ColorRes val buttonSecondaryBackgroundDisabledColorRes: Int,
    @ColorRes val buttonSecondaryBackgroundHighlightedColorRes: Int,
    @ColorRes val buttonSecondaryForegroundColorRes: Int,

    @ColorRes val buttonTertiaryBackgroundColorRes: Int,
    @ColorRes val buttonTertiaryBackgroundDisabledColorRes: Int,
    @ColorRes val buttonTertiaryBackgroundHighlightedColorRes: Int,
    @ColorRes val buttonTertiaryForegroundColorRes: Int,

    @ColorRes val buttonGreenBackgroundColorRes: Int,
    @ColorRes val buttonGreenBackgroundDisabledColorRes: Int,
    @ColorRes val buttonGreenBackgroundHighlightedColorRes: Int,

    @ColorRes val buttonOrangeBackgroundColorRes: Int,
    @ColorRes val buttonOrangeBackgroundDisabledColorRes: Int,
    @ColorRes val buttonOrangeBackgroundHighlightedColorRes: Int,

    @ColorRes val fieldBackgroundColorRes: Int,
    @ColorRes val fieldActiveBorderColorRes: Int,
    @ColorRes val fieldErrorBorderColorRes: Int,
    @ColorRes val fieldErrorBackgroundColorRes: Int,

    @ColorRes val accentBlueColorRes: Int,
    @ColorRes val accentGreenColorRes: Int,
    @ColorRes val accentRedColorRes: Int,
    @ColorRes val accentOrangeColorRes: Int,
    @ColorRes val accentPurpleColorRes: Int,

    @ColorRes val tabBarActiveIconColorRes: Int,
    @ColorRes val tabBarInactiveIconColorRes: Int,

    @ColorRes val separatorCommonColorRes: Int,
    @ColorRes val separatorAlternateColorRes: Int
) {

    data object BLUE : AppTheme(
        textPrimaryColorRes = R.color.textPrimaryBlue,
        textSecondaryColorRes = R.color.textSecondaryBlue,
        textTertiaryColorRes = R.color.textTertiaryBlue,
        textAccentColorRes = R.color.textAccentBlue,
        textPrimaryAlternateColorRes = R.color.textPrimaryAlternateBlue,
        backgroundPageColorRes = R.color.backgroundPageBlue,
        backgroundTransparentColorRes = R.color.backgroundTransparentBlue,
        backgroundContentColorRes = R.color.backgroundContentBlue,
        backgroundContentTintColorRes = R.color.backgroundContentTintBlue,
        backgroundContentAttentionColorRes = R.color.backgroundContentAttentionBlue,
        backgroundHighlightedColorRes = R.color.backgroundHighlightedBlue,
        backgroundOverlayStrongColorRes = R.color.backgroundOverlayStrongBlue,
        backgroundOverlayLightColorRes = R.color.backgroundOverlayLightBlue,
        backgroundOverlayExtraLightColorRes = R.color.backgroundOverlayExtraLightBlue,
        iconPrimaryColorRes = R.color.iconPrimaryBlue,
        iconSecondaryColorRes = R.color.iconSecondaryBlue,
        iconTertiaryColorRes = R.color.iconTertiaryBlue,
        iconPrimaryAlternateColorRes = R.color.iconPrimaryAlternateBlue,
        buttonPrimaryBackgroundColorRes = R.color.buttonPrimaryBackgroundBlue,
        buttonPrimaryBackgroundDisabledColorRes = R.color.buttonPrimaryBackgroundDisabledBlue,
        buttonPrimaryBackgroundHighlightedColorRes = R.color.buttonPrimaryBackgroundHighlightedBlue,
        buttonPrimaryForegroundColorRes = R.color.buttonPrimaryForegroundBlue,
        buttonSecondaryBackgroundColorRes = R.color.buttonSecondaryBackgroundBlue,
        buttonSecondaryBackgroundDisabledColorRes = R.color.buttonSecondaryBackgroundDisabledBlue,
        buttonSecondaryBackgroundHighlightedColorRes = R.color.buttonSecondaryBackgroundHighlightedBlue,
        buttonSecondaryForegroundColorRes = R.color.buttonSecondaryForegroundBlue,
        buttonTertiaryBackgroundColorRes = R.color.buttonTertiaryBackgroundBlue,
        buttonTertiaryBackgroundDisabledColorRes = R.color.buttonTertiaryBackgroundDisabledBlue,
        buttonTertiaryBackgroundHighlightedColorRes = R.color.buttonTertiaryBackgroundHighlightedBlue,
        buttonTertiaryForegroundColorRes = R.color.buttonTertiaryForegroundBlue,
        buttonGreenBackgroundColorRes = R.color.buttonGreenBackgroundBlue,
        buttonGreenBackgroundDisabledColorRes = R.color.buttonGreenBackgroundDisabledBlue,
        buttonGreenBackgroundHighlightedColorRes = R.color.buttonGreenBackgroundDisabledBlue,
        buttonOrangeBackgroundColorRes = R.color.buttonOrangeBackgroundBlue,
        buttonOrangeBackgroundDisabledColorRes = R.color.buttonOrangeBackgroundDisabledBlue,
        buttonOrangeBackgroundHighlightedColorRes = R.color.buttonOrangeBackgroundDisabledBlue,
        fieldBackgroundColorRes = R.color.fieldBackgroundBlue,
        fieldActiveBorderColorRes = R.color.fieldActiveBorderBlue,
        fieldErrorBorderColorRes = R.color.fieldErrorBorderBlue,
        fieldErrorBackgroundColorRes = R.color.fieldErrorBackgroundBlue,
        accentBlueColorRes = R.color.accentBlueBlue,
        accentGreenColorRes = R.color.accentGreenBlue,
        accentRedColorRes = R.color.accentRedBlue,
        accentOrangeColorRes = R.color.accentOrangeBlue,
        accentPurpleColorRes = R.color.accentPurpleBlue,
        tabBarActiveIconColorRes = R.color.tabBarActiveIconBlue,
        tabBarInactiveIconColorRes = R.color.tabBarInactiveIconBlue,
        separatorCommonColorRes = R.color.separatorCommonBlue,
        separatorAlternateColorRes = R.color.separatorAlternateBlue
    )

    data object DARK : AppTheme(
        textPrimaryColorRes = R.color.textPrimaryDark,
        textSecondaryColorRes = R.color.textSecondaryDark,
        textTertiaryColorRes = R.color.textTertiaryDark,
        textAccentColorRes = R.color.textAccentDark,
        textPrimaryAlternateColorRes = R.color.textPrimaryAlternateDark,
        backgroundPageColorRes = R.color.backgroundPageDark,
        backgroundTransparentColorRes = R.color.backgroundTransparentDark,
        backgroundContentColorRes = R.color.backgroundContentDark,
        backgroundContentTintColorRes = R.color.backgroundContentTintDark,
        backgroundContentAttentionColorRes = R.color.backgroundContentAttentionDark,
        backgroundHighlightedColorRes = R.color.backgroundHighlightedDark,
        backgroundOverlayStrongColorRes = R.color.backgroundOverlayStrongDark,
        backgroundOverlayLightColorRes = R.color.backgroundOverlayLightDark,
        backgroundOverlayExtraLightColorRes = R.color.backgroundOverlayExtraLightDark,
        iconPrimaryColorRes = R.color.iconPrimaryDark,
        iconSecondaryColorRes = R.color.iconSecondaryDark,
        iconTertiaryColorRes = R.color.iconTertiaryDark,
        iconPrimaryAlternateColorRes = R.color.iconPrimaryAlternateDark,
        buttonPrimaryBackgroundColorRes = R.color.buttonPrimaryBackgroundDark,
        buttonPrimaryBackgroundDisabledColorRes = R.color.buttonPrimaryBackgroundDisabledDark,
        buttonPrimaryBackgroundHighlightedColorRes = R.color.buttonPrimaryBackgroundHighlightedDark,
        buttonPrimaryForegroundColorRes = R.color.buttonPrimaryForegroundDark,
        buttonSecondaryBackgroundColorRes = R.color.buttonSecondaryBackgroundDark,
        buttonSecondaryBackgroundDisabledColorRes = R.color.buttonSecondaryBackgroundDisabledDark,
        buttonSecondaryBackgroundHighlightedColorRes = R.color.buttonSecondaryBackgroundHighlightedDark,
        buttonSecondaryForegroundColorRes = R.color.buttonSecondaryForegroundDark,
        buttonTertiaryBackgroundColorRes = R.color.buttonTertiaryBackgroundDark,
        buttonTertiaryBackgroundDisabledColorRes = R.color.buttonTertiaryBackgroundDisabledDark,
        buttonTertiaryBackgroundHighlightedColorRes = R.color.buttonTertiaryBackgroundHighlightedDark,
        buttonTertiaryForegroundColorRes = R.color.buttonTertiaryForegroundDark,
        buttonGreenBackgroundColorRes = R.color.buttonGreenBackgroundDark,
        buttonGreenBackgroundDisabledColorRes = R.color.buttonGreenBackgroundDisabledDark,
        buttonGreenBackgroundHighlightedColorRes = R.color.buttonGreenBackgroundDisabledDark,
        buttonOrangeBackgroundColorRes = R.color.buttonOrangeBackgroundDark,
        buttonOrangeBackgroundDisabledColorRes = R.color.buttonOrangeBackgroundDisabledDark,
        buttonOrangeBackgroundHighlightedColorRes = R.color.buttonOrangeBackgroundDisabledDark,
        fieldBackgroundColorRes = R.color.fieldBackgroundDark,
        fieldActiveBorderColorRes = R.color.fieldActiveBorderDark,
        fieldErrorBorderColorRes = R.color.fieldErrorBorderDark,
        fieldErrorBackgroundColorRes = R.color.fieldErrorBackgroundDark,
        accentBlueColorRes = R.color.accentBlueDark,
        accentGreenColorRes = R.color.accentGreenDark,
        accentRedColorRes = R.color.accentRedDark,
        accentOrangeColorRes = R.color.accentOrangeDark,
        accentPurpleColorRes = R.color.accentPurpleDark,
        tabBarActiveIconColorRes = R.color.tabBarActiveIconDark,
        tabBarInactiveIconColorRes = R.color.tabBarInactiveIconDark,
        separatorCommonColorRes = R.color.separatorCommonDark,
        separatorAlternateColorRes = R.color.separatorAlternateDark
    )

    data object LIGHT : AppTheme(
        textPrimaryColorRes = R.color.textPrimaryLight,
        textSecondaryColorRes = R.color.textSecondaryLight,
        textTertiaryColorRes = R.color.textTertiaryLight,
        textAccentColorRes = R.color.textAccentLight,
        textPrimaryAlternateColorRes = R.color.textPrimaryAlternateLight,
        backgroundPageColorRes = R.color.backgroundPageLight,
        backgroundTransparentColorRes = R.color.backgroundTransparentLight,
        backgroundContentColorRes = R.color.backgroundContentLight,
        backgroundContentTintColorRes = R.color.backgroundContentTintLight,
        backgroundContentAttentionColorRes = R.color.backgroundContentAttentionLight,
        backgroundHighlightedColorRes = R.color.backgroundHighlightedLight,
        backgroundOverlayStrongColorRes = R.color.backgroundOverlayStrongLight,
        backgroundOverlayLightColorRes = R.color.backgroundOverlayLightLight,
        backgroundOverlayExtraLightColorRes = R.color.backgroundOverlayExtraLightLight,
        iconPrimaryColorRes = R.color.iconPrimaryLight,
        iconSecondaryColorRes = R.color.iconSecondaryLight,
        iconTertiaryColorRes = R.color.iconTertiaryLight,
        iconPrimaryAlternateColorRes = R.color.iconPrimaryAlternateLight,
        buttonPrimaryBackgroundColorRes = R.color.buttonPrimaryBackgroundLight,
        buttonPrimaryBackgroundDisabledColorRes = R.color.buttonPrimaryBackgroundDisabledLight,
        buttonPrimaryBackgroundHighlightedColorRes = R.color.buttonPrimaryBackgroundHighlightedLight,
        buttonPrimaryForegroundColorRes = R.color.buttonPrimaryForegroundLight,
        buttonSecondaryBackgroundColorRes = R.color.buttonSecondaryBackgroundLight,
        buttonSecondaryBackgroundDisabledColorRes = R.color.buttonSecondaryBackgroundDisabledLight,
        buttonSecondaryBackgroundHighlightedColorRes = R.color.buttonSecondaryBackgroundHighlightedLight,
        buttonSecondaryForegroundColorRes = R.color.buttonSecondaryForegroundLight,
        buttonTertiaryBackgroundColorRes = R.color.buttonTertiaryBackgroundLight,
        buttonTertiaryBackgroundDisabledColorRes = R.color.buttonTertiaryBackgroundDisabledLight,
        buttonTertiaryBackgroundHighlightedColorRes = R.color.buttonTertiaryBackgroundHighlightedLight,
        buttonTertiaryForegroundColorRes = R.color.buttonTertiaryForegroundLight,
        buttonGreenBackgroundColorRes = R.color.buttonGreenBackgroundLight,
        buttonGreenBackgroundDisabledColorRes = R.color.buttonGreenBackgroundDisabledLight,
        buttonGreenBackgroundHighlightedColorRes = R.color.buttonGreenBackgroundDisabledLight,
        buttonOrangeBackgroundColorRes = R.color.buttonOrangeBackgroundLight,
        buttonOrangeBackgroundDisabledColorRes = R.color.buttonOrangeBackgroundDisabledLight,
        buttonOrangeBackgroundHighlightedColorRes = R.color.buttonOrangeBackgroundDisabledLight,
        fieldBackgroundColorRes = R.color.fieldBackgroundLight,
        fieldActiveBorderColorRes = R.color.fieldActiveBorderLight,
        fieldErrorBorderColorRes = R.color.fieldErrorBorderLight,
        fieldErrorBackgroundColorRes = R.color.fieldErrorBackgroundLight,
        accentBlueColorRes = R.color.accentBlueLight,
        accentGreenColorRes = R.color.accentGreenLight,
        accentRedColorRes = R.color.accentRedLight,
        accentOrangeColorRes = R.color.accentOrangeLight,
        accentPurpleColorRes = R.color.accentPurpleLight,
        tabBarActiveIconColorRes = R.color.tabBarActiveIconLight,
        tabBarInactiveIconColorRes = R.color.tabBarInactiveIconLight,
        separatorCommonColorRes = R.color.separatorCommonLight,
        separatorAlternateColorRes = R.color.separatorAlternateLight
    )

    val isDark: Boolean get() = this is DARK
}