name: Android Beta Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  beta-build:
    name: Build Beta APK
    uses: ./.github/workflows/build-apk-reusable.yml
    with:
      gradle-task: :apps:wallet:instance:main:assembleDefaultRelease
      artifact-name-prefix: tonkeeper-beta
      apk-path-glob: apps/wallet/instance/main/build/outputs/apk/default/release/*.apk
      signing-mode: release
    secrets: inherit
