name: Android Debug Build

on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    paths-ignore:
      - '**.md'
  # Mon-Fri.
  schedule:
    - cron: '0 6,9,12,15 * * 1-5'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  debug-build:
    name: Build Debug APK
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/build-apk-reusable.yml
    with:
      gradle-task: :apps:wallet:instance:main:assembleDefaultDebug
      artifact-name-prefix: tonkeeper-debug
      apk-path-glob: apps/wallet/instance/main/build/outputs/apk/default/debug/*.apk
      gradle-cache: true
      artifact-retention-days: 7
      inject-version-code: false
    secrets: inherit
