name: Android Publish
run-name: Android Publish ${{ inputs.version_name || github.event.release.tag_name }}

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (e.g. 1.2.3). Required for manual runs.'
        required: true
        type: string

jobs:
  android-build:
    name: android-build
    runs-on: macos-latest-xlarge
    permissions:
      contents: write

    steps:
      - name: Checkout to git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set VERSION_NAME
        run: echo "VERSION_NAME=${{ inputs.version_name || github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Set up ruby env
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.ANDROID_DIST_SIGNING_KEY }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > google-release.keystore

      - name: Build android beta
        run: bundle exec fastlane android beta
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=false -Dorg.gradle.configuration-cache=false"
          KEYSTORE_FILE: ${{ github.workspace }}/google-release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.TONKEEPER_UPLOAD_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.TONKEEPER_UPLOAD_KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.TONKEEPER_UPLOAD_KEY_PASSWORD }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}

      - name: Add build title to summary
        run: echo "### ${{ env.VERSION_NAME }}_${{ env.VERSION_CODE }}" >> $GITHUB_STEP_SUMMARY

      - name: Create and push git tag
        run: |
          TAG="v${VERSION_NAME}_${VERSION_CODE}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Upload android aab to artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Tonkeeper aab ${{ env.VERSION_CODE }}
          path: |
            ${{ env.AAB_OUTPUT_PATH }}

      - name: Upload android apk to artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Tonkeeper apk ${{ env.VERSION_CODE }}
          path: |
            ${{ env.APK_OUTPUT_PATH }}
