name: Android APK release CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: apk-release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 20.0.2+9

      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.ANDROID_DIST_SIGNING_KEY }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > google-release.keystore

      - name: Build android beta
        run: bundle exec fastlane android beta
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/google-release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.TONKEEPER_UPLOAD_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.TONKEEPER_UPLOAD_KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.TONKEEPER_UPLOAD_KEY_PASSWORD }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}

      - name: Upload android aab to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Tonkeeper aab ${{ env.VERSION_CODE }}
          path: |
            ${{ env.AAB_OUTPUT_PATH }}

      - name: Upload android apk to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Tonkeeper apk ${{ env.VERSION_CODE }}
          path: |
            ${{ env.APK_OUTPUT_PATH }}

      - name: Fix filename
        run: |
          mkdir -p release
          cp "$APK_OUTPUT_PATH" release/Tonkeeper.apk

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: release/Tonkeeper.apk

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with: { name: apk }

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Tonkeeper.apk